package org.spongycastle.crypto.engines;

import org.spongycastle.util.Pack;

public final class SerpentEngine extends SerpentEngineBase {
    /* access modifiers changed from: protected */
    public int[] q(byte[] key) {
        byte[] bArr = key;
        int[] kPad = new int[16];
        int length = 0;
        int off = 0;
        while (off + 4 < bArr.length) {
            kPad[length] = Pack.j(bArr, off);
            off += 4;
            length++;
        }
        if (off % 4 == 0) {
            int length2 = length + 1;
            kPad[length] = Pack.j(bArr, off);
            if (length2 < 8) {
                kPad[length2] = 1;
            }
            int[] w = new int[132];
            for (int i = 8; i < 16; i++) {
                kPad[i] = SerpentEngineBase.r((-1640531527 ^ (((kPad[i - 8] ^ kPad[i - 5]) ^ kPad[i - 3]) ^ kPad[i - 1])) ^ (i - 8), 11);
            }
            System.arraycopy(kPad, 8, w, 0, 8);
            for (int i2 = 8; i2 < 132; i2++) {
                w[i2] = SerpentEngineBase.r(((((w[i2 - 8] ^ w[i2 - 5]) ^ w[i2 - 3]) ^ w[i2 - 1]) ^ -1640531527) ^ i2, 11);
            }
            w(w[0], w[1], w[2], w[3]);
            w[0] = this.c;
            w[1] = this.d;
            w[2] = this.e;
            w[3] = this.f;
            v(w[4], w[5], w[6], w[7]);
            w[4] = this.c;
            w[5] = this.d;
            w[6] = this.e;
            w[7] = this.f;
            u(w[8], w[9], w[10], w[11]);
            w[8] = this.c;
            w[9] = this.d;
            w[10] = this.e;
            w[11] = this.f;
            t(w[12], w[13], w[14], w[15]);
            w[12] = this.c;
            w[13] = this.d;
            w[14] = this.e;
            w[15] = this.f;
            A(w[16], w[17], w[18], w[19]);
            w[16] = this.c;
            w[17] = this.d;
            w[18] = this.e;
            w[19] = this.f;
            z(w[20], w[21], w[22], w[23]);
            w[20] = this.c;
            w[21] = this.d;
            w[22] = this.e;
            w[23] = this.f;
            y(w[24], w[25], w[26], w[27]);
            w[24] = this.c;
            w[25] = this.d;
            w[26] = this.e;
            w[27] = this.f;
            x(w[28], w[29], w[30], w[31]);
            w[28] = this.c;
            w[29] = this.d;
            w[30] = this.e;
            w[31] = this.f;
            w(w[32], w[33], w[34], w[35]);
            w[32] = this.c;
            w[33] = this.d;
            w[34] = this.e;
            w[35] = this.f;
            v(w[36], w[37], w[38], w[39]);
            w[36] = this.c;
            w[37] = this.d;
            w[38] = this.e;
            w[39] = this.f;
            u(w[40], w[41], w[42], w[43]);
            w[40] = this.c;
            w[41] = this.d;
            w[42] = this.e;
            w[43] = this.f;
            t(w[44], w[45], w[46], w[47]);
            w[44] = this.c;
            w[45] = this.d;
            w[46] = this.e;
            w[47] = this.f;
            A(w[48], w[49], w[50], w[51]);
            w[48] = this.c;
            w[49] = this.d;
            w[50] = this.e;
            w[51] = this.f;
            z(w[52], w[53], w[54], w[55]);
            w[52] = this.c;
            w[53] = this.d;
            w[54] = this.e;
            w[55] = this.f;
            y(w[56], w[57], w[58], w[59]);
            w[56] = this.c;
            w[57] = this.d;
            w[58] = this.e;
            w[59] = this.f;
            x(w[60], w[61], w[62], w[63]);
            w[60] = this.c;
            w[61] = this.d;
            w[62] = this.e;
            w[63] = this.f;
            w(w[64], w[65], w[66], w[67]);
            w[64] = this.c;
            w[65] = this.d;
            w[66] = this.e;
            w[67] = this.f;
            v(w[68], w[69], w[70], w[71]);
            w[68] = this.c;
            w[69] = this.d;
            w[70] = this.e;
            w[71] = this.f;
            u(w[72], w[73], w[74], w[75]);
            w[72] = this.c;
            w[73] = this.d;
            w[74] = this.e;
            w[75] = this.f;
            t(w[76], w[77], w[78], w[79]);
            w[76] = this.c;
            w[77] = this.d;
            w[78] = this.e;
            w[79] = this.f;
            A(w[80], w[81], w[82], w[83]);
            w[80] = this.c;
            w[81] = this.d;
            w[82] = this.e;
            w[83] = this.f;
            z(w[84], w[85], w[86], w[87]);
            w[84] = this.c;
            w[85] = this.d;
            w[86] = this.e;
            w[87] = this.f;
            y(w[88], w[89], w[90], w[91]);
            w[88] = this.c;
            w[89] = this.d;
            w[90] = this.e;
            w[91] = this.f;
            x(w[92], w[93], w[94], w[95]);
            w[92] = this.c;
            w[93] = this.d;
            w[94] = this.e;
            w[95] = this.f;
            w(w[96], w[97], w[98], w[99]);
            w[96] = this.c;
            w[97] = this.d;
            w[98] = this.e;
            w[99] = this.f;
            v(w[100], w[101], w[102], w[103]);
            w[100] = this.c;
            w[101] = this.d;
            w[102] = this.e;
            w[103] = this.f;
            u(w[104], w[105], w[106], w[107]);
            w[104] = this.c;
            w[105] = this.d;
            w[106] = this.e;
            w[107] = this.f;
            t(w[108], w[109], w[110], w[111]);
            w[108] = this.c;
            w[109] = this.d;
            w[110] = this.e;
            w[111] = this.f;
            A(w[112], w[113], w[114], w[115]);
            w[112] = this.c;
            w[113] = this.d;
            w[114] = this.e;
            w[115] = this.f;
            z(w[116], w[117], w[118], w[119]);
            w[116] = this.c;
            w[117] = this.d;
            w[118] = this.e;
            w[119] = this.f;
            y(w[120], w[121], w[122], w[123]);
            w[120] = this.c;
            w[121] = this.d;
            w[122] = this.e;
            w[123] = this.f;
            x(w[124], w[125], w[126], w[127]);
            w[124] = this.c;
            w[125] = this.d;
            w[126] = this.e;
            w[127] = this.f;
            w(w[128], w[129], w[130], w[131]);
            w[128] = this.c;
            w[129] = this.d;
            w[130] = this.e;
            w[131] = this.f;
            return w;
        }
        throw new IllegalArgumentException("key must be a multiple of 4 bytes");
    }

    /* access modifiers changed from: protected */
    public void g(byte[] input, int inOff, byte[] output, int outOff) {
        this.c = Pack.j(input, inOff);
        this.d = Pack.j(input, inOff + 4);
        this.e = Pack.j(input, inOff + 8);
        int j = Pack.j(input, inOff + 12);
        this.f = j;
        int[] iArr = this.b;
        t(iArr[0] ^ this.c, iArr[1] ^ this.d, iArr[2] ^ this.e, j ^ iArr[3]);
        d();
        int[] iArr2 = this.b;
        u(iArr2[4] ^ this.c, iArr2[5] ^ this.d, iArr2[6] ^ this.e, iArr2[7] ^ this.f);
        d();
        int[] iArr3 = this.b;
        v(iArr3[8] ^ this.c, iArr3[9] ^ this.d, iArr3[10] ^ this.e, iArr3[11] ^ this.f);
        d();
        int[] iArr4 = this.b;
        w(iArr4[12] ^ this.c, iArr4[13] ^ this.d, iArr4[14] ^ this.e, iArr4[15] ^ this.f);
        d();
        int[] iArr5 = this.b;
        x(iArr5[16] ^ this.c, iArr5[17] ^ this.d, iArr5[18] ^ this.e, iArr5[19] ^ this.f);
        d();
        int[] iArr6 = this.b;
        y(iArr6[20] ^ this.c, iArr6[21] ^ this.d, iArr6[22] ^ this.e, iArr6[23] ^ this.f);
        d();
        int[] iArr7 = this.b;
        z(iArr7[24] ^ this.c, iArr7[25] ^ this.d, iArr7[26] ^ this.e, iArr7[27] ^ this.f);
        d();
        int[] iArr8 = this.b;
        A(iArr8[28] ^ this.c, iArr8[29] ^ this.d, iArr8[30] ^ this.e, iArr8[31] ^ this.f);
        d();
        int[] iArr9 = this.b;
        t(iArr9[32] ^ this.c, iArr9[33] ^ this.d, iArr9[34] ^ this.e, iArr9[35] ^ this.f);
        d();
        int[] iArr10 = this.b;
        u(iArr10[36] ^ this.c, iArr10[37] ^ this.d, iArr10[38] ^ this.e, iArr10[39] ^ this.f);
        d();
        int[] iArr11 = this.b;
        v(iArr11[40] ^ this.c, iArr11[41] ^ this.d, iArr11[42] ^ this.e, iArr11[43] ^ this.f);
        d();
        int[] iArr12 = this.b;
        w(iArr12[44] ^ this.c, iArr12[45] ^ this.d, iArr12[46] ^ this.e, iArr12[47] ^ this.f);
        d();
        int[] iArr13 = this.b;
        x(iArr13[48] ^ this.c, iArr13[49] ^ this.d, iArr13[50] ^ this.e, iArr13[51] ^ this.f);
        d();
        int[] iArr14 = this.b;
        y(iArr14[52] ^ this.c, iArr14[53] ^ this.d, iArr14[54] ^ this.e, iArr14[55] ^ this.f);
        d();
        int[] iArr15 = this.b;
        z(iArr15[56] ^ this.c, iArr15[57] ^ this.d, iArr15[58] ^ this.e, iArr15[59] ^ this.f);
        d();
        int[] iArr16 = this.b;
        A(iArr16[60] ^ this.c, iArr16[61] ^ this.d, iArr16[62] ^ this.e, iArr16[63] ^ this.f);
        d();
        int[] iArr17 = this.b;
        t(iArr17[64] ^ this.c, iArr17[65] ^ this.d, iArr17[66] ^ this.e, iArr17[67] ^ this.f);
        d();
        int[] iArr18 = this.b;
        u(iArr18[68] ^ this.c, iArr18[69] ^ this.d, iArr18[70] ^ this.e, iArr18[71] ^ this.f);
        d();
        int[] iArr19 = this.b;
        v(iArr19[72] ^ this.c, iArr19[73] ^ this.d, iArr19[74] ^ this.e, iArr19[75] ^ this.f);
        d();
        int[] iArr20 = this.b;
        w(iArr20[76] ^ this.c, iArr20[77] ^ this.d, iArr20[78] ^ this.e, iArr20[79] ^ this.f);
        d();
        int[] iArr21 = this.b;
        x(iArr21[80] ^ this.c, iArr21[81] ^ this.d, iArr21[82] ^ this.e, iArr21[83] ^ this.f);
        d();
        int[] iArr22 = this.b;
        y(iArr22[84] ^ this.c, iArr22[85] ^ this.d, iArr22[86] ^ this.e, iArr22[87] ^ this.f);
        d();
        int[] iArr23 = this.b;
        z(iArr23[88] ^ this.c, iArr23[89] ^ this.d, iArr23[90] ^ this.e, iArr23[91] ^ this.f);
        d();
        int[] iArr24 = this.b;
        A(iArr24[92] ^ this.c, iArr24[93] ^ this.d, iArr24[94] ^ this.e, iArr24[95] ^ this.f);
        d();
        int[] iArr25 = this.b;
        t(iArr25[96] ^ this.c, iArr25[97] ^ this.d, iArr25[98] ^ this.e, iArr25[99] ^ this.f);
        d();
        int[] iArr26 = this.b;
        u(iArr26[100] ^ this.c, iArr26[101] ^ this.d, iArr26[102] ^ this.e, iArr26[103] ^ this.f);
        d();
        int[] iArr27 = this.b;
        v(iArr27[104] ^ this.c, iArr27[105] ^ this.d, iArr27[106] ^ this.e, iArr27[107] ^ this.f);
        d();
        int[] iArr28 = this.b;
        w(iArr28[108] ^ this.c, iArr28[109] ^ this.d, iArr28[110] ^ this.e, iArr28[111] ^ this.f);
        d();
        int[] iArr29 = this.b;
        x(iArr29[112] ^ this.c, iArr29[113] ^ this.d, iArr29[114] ^ this.e, iArr29[115] ^ this.f);
        d();
        int[] iArr30 = this.b;
        y(iArr30[116] ^ this.c, iArr30[117] ^ this.d, iArr30[118] ^ this.e, iArr30[119] ^ this.f);
        d();
        int[] iArr31 = this.b;
        z(iArr31[120] ^ this.c, iArr31[121] ^ this.d, iArr31[122] ^ this.e, iArr31[123] ^ this.f);
        d();
        int[] iArr32 = this.b;
        A(iArr32[124] ^ this.c, iArr32[125] ^ this.d, iArr32[126] ^ this.e, iArr32[127] ^ this.f);
        Pack.h(this.b[128] ^ this.c, output, outOff);
        Pack.h(this.b[129] ^ this.d, output, outOff + 4);
        Pack.h(this.b[130] ^ this.e, output, outOff + 8);
        Pack.h(this.b[131] ^ this.f, output, outOff + 12);
    }

    /* access modifiers changed from: protected */
    public void e(byte[] input, int inOff, byte[] output, int outOff) {
        this.c = this.b[128] ^ Pack.j(input, inOff);
        this.d = this.b[129] ^ Pack.j(input, inOff + 4);
        this.e = this.b[130] ^ Pack.j(input, inOff + 8);
        int j = this.b[131] ^ Pack.j(input, inOff + 12);
        this.f = j;
        o(this.c, this.d, this.e, j);
        int i = this.c;
        int[] iArr = this.b;
        this.c = i ^ iArr[124];
        this.d ^= iArr[125];
        this.e ^= iArr[126];
        this.f ^= iArr[127];
        p();
        n(this.c, this.d, this.e, this.f);
        int i2 = this.c;
        int[] iArr2 = this.b;
        this.c = i2 ^ iArr2[120];
        this.d ^= iArr2[121];
        this.e ^= iArr2[122];
        this.f ^= iArr2[123];
        p();
        m(this.c, this.d, this.e, this.f);
        int i3 = this.c;
        int[] iArr3 = this.b;
        this.c = i3 ^ iArr3[116];
        this.d ^= iArr3[117];
        this.e ^= iArr3[118];
        this.f ^= iArr3[119];
        p();
        l(this.c, this.d, this.e, this.f);
        int i4 = this.c;
        int[] iArr4 = this.b;
        this.c = i4 ^ iArr4[112];
        this.d ^= iArr4[113];
        this.e ^= iArr4[114];
        this.f ^= iArr4[115];
        p();
        k(this.c, this.d, this.e, this.f);
        int i5 = this.c;
        int[] iArr5 = this.b;
        this.c = i5 ^ iArr5[108];
        this.d ^= iArr5[109];
        this.e ^= iArr5[110];
        this.f ^= iArr5[111];
        p();
        j(this.c, this.d, this.e, this.f);
        int i6 = this.c;
        int[] iArr6 = this.b;
        this.c = i6 ^ iArr6[104];
        this.d ^= iArr6[105];
        this.e ^= iArr6[106];
        this.f ^= iArr6[107];
        p();
        i(this.c, this.d, this.e, this.f);
        int i7 = this.c;
        int[] iArr7 = this.b;
        this.c = i7 ^ iArr7[100];
        this.d ^= iArr7[101];
        this.e ^= iArr7[102];
        this.f ^= iArr7[103];
        p();
        h(this.c, this.d, this.e, this.f);
        int i8 = this.c;
        int[] iArr8 = this.b;
        this.c = i8 ^ iArr8[96];
        this.d ^= iArr8[97];
        this.e ^= iArr8[98];
        this.f ^= iArr8[99];
        p();
        o(this.c, this.d, this.e, this.f);
        int i9 = this.c;
        int[] iArr9 = this.b;
        this.c = i9 ^ iArr9[92];
        this.d ^= iArr9[93];
        this.e ^= iArr9[94];
        this.f ^= iArr9[95];
        p();
        n(this.c, this.d, this.e, this.f);
        int i10 = this.c;
        int[] iArr10 = this.b;
        this.c = i10 ^ iArr10[88];
        this.d ^= iArr10[89];
        this.e ^= iArr10[90];
        this.f ^= iArr10[91];
        p();
        m(this.c, this.d, this.e, this.f);
        int i11 = this.c;
        int[] iArr11 = this.b;
        this.c = i11 ^ iArr11[84];
        this.d ^= iArr11[85];
        this.e ^= iArr11[86];
        this.f ^= iArr11[87];
        p();
        l(this.c, this.d, this.e, this.f);
        int i12 = this.c;
        int[] iArr12 = this.b;
        this.c = i12 ^ iArr12[80];
        this.d ^= iArr12[81];
        this.e ^= iArr12[82];
        this.f ^= iArr12[83];
        p();
        k(this.c, this.d, this.e, this.f);
        int i13 = this.c;
        int[] iArr13 = this.b;
        this.c = i13 ^ iArr13[76];
        this.d ^= iArr13[77];
        this.e ^= iArr13[78];
        this.f ^= iArr13[79];
        p();
        j(this.c, this.d, this.e, this.f);
        int i14 = this.c;
        int[] iArr14 = this.b;
        this.c = i14 ^ iArr14[72];
        this.d ^= iArr14[73];
        this.e ^= iArr14[74];
        this.f ^= iArr14[75];
        p();
        i(this.c, this.d, this.e, this.f);
        int i15 = this.c;
        int[] iArr15 = this.b;
        this.c = i15 ^ iArr15[68];
        this.d ^= iArr15[69];
        this.e ^= iArr15[70];
        this.f ^= iArr15[71];
        p();
        h(this.c, this.d, this.e, this.f);
        int i16 = this.c;
        int[] iArr16 = this.b;
        this.c = i16 ^ iArr16[64];
        this.d ^= iArr16[65];
        this.e ^= iArr16[66];
        this.f ^= iArr16[67];
        p();
        o(this.c, this.d, this.e, this.f);
        int i17 = this.c;
        int[] iArr17 = this.b;
        this.c = i17 ^ iArr17[60];
        this.d ^= iArr17[61];
        this.e ^= iArr17[62];
        this.f ^= iArr17[63];
        p();
        n(this.c, this.d, this.e, this.f);
        int i18 = this.c;
        int[] iArr18 = this.b;
        this.c = i18 ^ iArr18[56];
        this.d ^= iArr18[57];
        this.e ^= iArr18[58];
        this.f ^= iArr18[59];
        p();
        m(this.c, this.d, this.e, this.f);
        int i19 = this.c;
        int[] iArr19 = this.b;
        this.c = i19 ^ iArr19[52];
        this.d ^= iArr19[53];
        this.e ^= iArr19[54];
        this.f ^= iArr19[55];
        p();
        l(this.c, this.d, this.e, this.f);
        int i20 = this.c;
        int[] iArr20 = this.b;
        this.c = i20 ^ iArr20[48];
        this.d ^= iArr20[49];
        this.e ^= iArr20[50];
        this.f ^= iArr20[51];
        p();
        k(this.c, this.d, this.e, this.f);
        int i21 = this.c;
        int[] iArr21 = this.b;
        this.c = i21 ^ iArr21[44];
        this.d ^= iArr21[45];
        this.e ^= iArr21[46];
        this.f ^= iArr21[47];
        p();
        j(this.c, this.d, this.e, this.f);
        int i22 = this.c;
        int[] iArr22 = this.b;
        this.c = i22 ^ iArr22[40];
        this.d ^= iArr22[41];
        this.e ^= iArr22[42];
        this.f ^= iArr22[43];
        p();
        i(this.c, this.d, this.e, this.f);
        int i23 = this.c;
        int[] iArr23 = this.b;
        this.c = i23 ^ iArr23[36];
        this.d ^= iArr23[37];
        this.e ^= iArr23[38];
        this.f ^= iArr23[39];
        p();
        h(this.c, this.d, this.e, this.f);
        int i24 = this.c;
        int[] iArr24 = this.b;
        this.c = i24 ^ iArr24[32];
        this.d ^= iArr24[33];
        this.e ^= iArr24[34];
        this.f ^= iArr24[35];
        p();
        o(this.c, this.d, this.e, this.f);
        int i25 = this.c;
        int[] iArr25 = this.b;
        this.c = i25 ^ iArr25[28];
        this.d ^= iArr25[29];
        this.e ^= iArr25[30];
        this.f ^= iArr25[31];
        p();
        n(this.c, this.d, this.e, this.f);
        int i26 = this.c;
        int[] iArr26 = this.b;
        this.c = i26 ^ iArr26[24];
        this.d ^= iArr26[25];
        this.e ^= iArr26[26];
        this.f ^= iArr26[27];
        p();
        m(this.c, this.d, this.e, this.f);
        int i27 = this.c;
        int[] iArr27 = this.b;
        this.c = i27 ^ iArr27[20];
        this.d ^= iArr27[21];
        this.e ^= iArr27[22];
        this.f ^= iArr27[23];
        p();
        l(this.c, this.d, this.e, this.f);
        int i28 = this.c;
        int[] iArr28 = this.b;
        this.c = i28 ^ iArr28[16];
        this.d ^= iArr28[17];
        this.e ^= iArr28[18];
        this.f ^= iArr28[19];
        p();
        k(this.c, this.d, this.e, this.f);
        int i29 = this.c;
        int[] iArr29 = this.b;
        this.c = i29 ^ iArr29[12];
        this.d ^= iArr29[13];
        this.e ^= iArr29[14];
        this.f ^= iArr29[15];
        p();
        j(this.c, this.d, this.e, this.f);
        int i30 = this.c;
        int[] iArr30 = this.b;
        this.c = i30 ^ iArr30[8];
        this.d ^= iArr30[9];
        this.e ^= iArr30[10];
        this.f ^= iArr30[11];
        p();
        i(this.c, this.d, this.e, this.f);
        int i31 = this.c;
        int[] iArr31 = this.b;
        this.c = i31 ^ iArr31[4];
        this.d ^= iArr31[5];
        this.e ^= iArr31[6];
        this.f ^= iArr31[7];
        p();
        h(this.c, this.d, this.e, this.f);
        Pack.h(this.c ^ this.b[0], output, outOff);
        Pack.h(this.d ^ this.b[1], output, outOff + 4);
        Pack.h(this.e ^ this.b[2], output, outOff + 8);
        Pack.h(this.f ^ this.b[3], output, outOff + 12);
    }
}
