package org.spongycastle.asn1.gm;

import androidx.exifinterface.media.ExifInterface;
import org.spongycastle.asn1.ASN1ObjectIdentifier;

public interface GMObjectIdentifiers {
    public static final ASN1ObjectIdentifier A;
    public static final ASN1ObjectIdentifier B;
    public static final ASN1ObjectIdentifier C;
    public static final ASN1ObjectIdentifier D;
    public static final ASN1ObjectIdentifier E;
    public static final ASN1ObjectIdentifier F;
    public static final ASN1ObjectIdentifier G;
    public static final ASN1ObjectIdentifier H;
    public static final ASN1ObjectIdentifier I;
    public static final ASN1ObjectIdentifier J;
    public static final ASN1ObjectIdentifier K;
    public static final ASN1ObjectIdentifier L;
    public static final ASN1ObjectIdentifier M;
    public static final ASN1ObjectIdentifier N;
    public static final ASN1ObjectIdentifier O;
    public static final ASN1ObjectIdentifier P;
    public static final ASN1ObjectIdentifier Q;
    public static final ASN1ObjectIdentifier R;
    public static final ASN1ObjectIdentifier S;
    public static final ASN1ObjectIdentifier T;
    public static final ASN1ObjectIdentifier U;
    public static final ASN1ObjectIdentifier V;
    public static final ASN1ObjectIdentifier W;
    public static final ASN1ObjectIdentifier X;
    public static final ASN1ObjectIdentifier Y;
    public static final ASN1ObjectIdentifier Z;
    public static final ASN1ObjectIdentifier a;
    public static final ASN1ObjectIdentifier a0;
    public static final ASN1ObjectIdentifier b;
    public static final ASN1ObjectIdentifier b0;
    public static final ASN1ObjectIdentifier c;
    public static final ASN1ObjectIdentifier c0;
    public static final ASN1ObjectIdentifier d;
    public static final ASN1ObjectIdentifier d0;
    public static final ASN1ObjectIdentifier e;
    public static final ASN1ObjectIdentifier e0;
    public static final ASN1ObjectIdentifier f;
    public static final ASN1ObjectIdentifier f0;
    public static final ASN1ObjectIdentifier g;
    public static final ASN1ObjectIdentifier g0;
    public static final ASN1ObjectIdentifier h;
    public static final ASN1ObjectIdentifier h0;
    public static final ASN1ObjectIdentifier i;
    public static final ASN1ObjectIdentifier i0;
    public static final ASN1ObjectIdentifier j;
    public static final ASN1ObjectIdentifier j0;
    public static final ASN1ObjectIdentifier k;
    public static final ASN1ObjectIdentifier k0;
    public static final ASN1ObjectIdentifier l;
    public static final ASN1ObjectIdentifier l0;
    public static final ASN1ObjectIdentifier m;
    public static final ASN1ObjectIdentifier m0;
    public static final ASN1ObjectIdentifier n;
    public static final ASN1ObjectIdentifier o;
    public static final ASN1ObjectIdentifier p;
    public static final ASN1ObjectIdentifier q;
    public static final ASN1ObjectIdentifier r;
    public static final ASN1ObjectIdentifier s;
    public static final ASN1ObjectIdentifier t;
    public static final ASN1ObjectIdentifier u;
    public static final ASN1ObjectIdentifier v;
    public static final ASN1ObjectIdentifier w;
    public static final ASN1ObjectIdentifier x;
    public static final ASN1ObjectIdentifier y;
    public static final ASN1ObjectIdentifier z;

    static {
        ASN1ObjectIdentifier aSN1ObjectIdentifier = new ASN1ObjectIdentifier("1.2.156.10197.1");
        a = aSN1ObjectIdentifier;
        b = aSN1ObjectIdentifier.o("101.1");
        c = aSN1ObjectIdentifier.o("101.2");
        d = aSN1ObjectIdentifier.o("101.3");
        e = aSN1ObjectIdentifier.o("101.4");
        f = aSN1ObjectIdentifier.o("102.1");
        g = aSN1ObjectIdentifier.o("102.2");
        h = aSN1ObjectIdentifier.o("102.3");
        i = aSN1ObjectIdentifier.o("102.4");
        j = aSN1ObjectIdentifier.o("102.5");
        k = aSN1ObjectIdentifier.o("102.6");
        l = aSN1ObjectIdentifier.o("103.1");
        m = aSN1ObjectIdentifier.o("103.2");
        n = aSN1ObjectIdentifier.o("103.3");
        o = aSN1ObjectIdentifier.o("103.4");
        p = aSN1ObjectIdentifier.o("103.5");
        q = aSN1ObjectIdentifier.o("103.6");
        r = aSN1ObjectIdentifier.o("104.1");
        s = aSN1ObjectIdentifier.o("104.2");
        t = aSN1ObjectIdentifier.o("104.3");
        u = aSN1ObjectIdentifier.o("104.4");
        v = aSN1ObjectIdentifier.o("104.5");
        w = aSN1ObjectIdentifier.o("104.6");
        x = aSN1ObjectIdentifier.o("104.7");
        y = aSN1ObjectIdentifier.o("104.8");
        z = aSN1ObjectIdentifier.o("104.9");
        A = aSN1ObjectIdentifier.o("104.10");
        B = aSN1ObjectIdentifier.o("104.11");
        C = aSN1ObjectIdentifier.o("104.12");
        D = aSN1ObjectIdentifier.o("104.100");
        E = aSN1ObjectIdentifier.o("201");
        F = aSN1ObjectIdentifier.o("301");
        G = aSN1ObjectIdentifier.o("301.1");
        H = aSN1ObjectIdentifier.o("301.2");
        ASN1ObjectIdentifier o2 = aSN1ObjectIdentifier.o("301.3");
        I = o2;
        J = aSN1ObjectIdentifier.o("301.101");
        K = o2.o("1");
        L = o2.o(ExifInterface.GPS_MEASUREMENT_2D);
        M = o2.o("2.1");
        N = o2.o("2.2");
        O = o2.o("2.3");
        P = o2.o("2.4");
        Q = o2.o("2.5");
        R = o2.o("2.6");
        S = o2.o("2.7");
        T = o2.o("2.8");
        U = o2.o("2.9");
        V = o2.o("2.10");
        W = o2.o("2.11");
        X = aSN1ObjectIdentifier.o("302");
        Y = aSN1ObjectIdentifier.o("302.1");
        ASN1ObjectIdentifier aSN1ObjectIdentifier2 = a;
        Z = aSN1ObjectIdentifier2.o("302.2");
        a0 = aSN1ObjectIdentifier2.o("302.3");
        ASN1ObjectIdentifier o3 = aSN1ObjectIdentifier2.o("401");
        b0 = o3;
        c0 = o3.o(ExifInterface.GPS_MEASUREMENT_2D);
        d0 = aSN1ObjectIdentifier2.o("501");
        e0 = aSN1ObjectIdentifier2.o("502");
        f0 = aSN1ObjectIdentifier2.o("503");
        g0 = aSN1ObjectIdentifier2.o("504");
        h0 = aSN1ObjectIdentifier2.o("505");
        i0 = aSN1ObjectIdentifier2.o("506");
        j0 = aSN1ObjectIdentifier2.o("507");
        k0 = aSN1ObjectIdentifier2.o("520");
        l0 = aSN1ObjectIdentifier2.o("521");
        m0 = aSN1ObjectIdentifier2.o("522");
    }
}
