package org.spongycastle.asn1.nsri;

import androidx.exifinterface.media.ExifInterface;
import androidx.room.RoomMasterTable;
import com.sensorsdata.analytics.android.sdk.data.adapter.DbParams;
import org.spongycastle.asn1.ASN1ObjectIdentifier;

public interface NSRIObjectIdentifiers {
    public static final ASN1ObjectIdentifier A;
    public static final ASN1ObjectIdentifier B;
    public static final ASN1ObjectIdentifier C;
    public static final ASN1ObjectIdentifier D;
    public static final ASN1ObjectIdentifier E;
    public static final ASN1ObjectIdentifier F;
    public static final ASN1ObjectIdentifier G;
    public static final ASN1ObjectIdentifier H;
    public static final ASN1ObjectIdentifier I;
    public static final ASN1ObjectIdentifier J;
    public static final ASN1ObjectIdentifier K;
    public static final ASN1ObjectIdentifier L;
    public static final ASN1ObjectIdentifier M;
    public static final ASN1ObjectIdentifier a;
    public static final ASN1ObjectIdentifier b;
    public static final ASN1ObjectIdentifier c;
    public static final ASN1ObjectIdentifier d;
    public static final ASN1ObjectIdentifier e;
    public static final ASN1ObjectIdentifier f;
    public static final ASN1ObjectIdentifier g;
    public static final ASN1ObjectIdentifier h;
    public static final ASN1ObjectIdentifier i;
    public static final ASN1ObjectIdentifier j;
    public static final ASN1ObjectIdentifier k;
    public static final ASN1ObjectIdentifier l;
    public static final ASN1ObjectIdentifier m;
    public static final ASN1ObjectIdentifier n;
    public static final ASN1ObjectIdentifier o;
    public static final ASN1ObjectIdentifier p;
    public static final ASN1ObjectIdentifier q;
    public static final ASN1ObjectIdentifier r;
    public static final ASN1ObjectIdentifier s;
    public static final ASN1ObjectIdentifier t;
    public static final ASN1ObjectIdentifier u;
    public static final ASN1ObjectIdentifier v;
    public static final ASN1ObjectIdentifier w;
    public static final ASN1ObjectIdentifier x;
    public static final ASN1ObjectIdentifier y;
    public static final ASN1ObjectIdentifier z;

    static {
        ASN1ObjectIdentifier aSN1ObjectIdentifier = new ASN1ObjectIdentifier("1.2.410.200046");
        a = aSN1ObjectIdentifier;
        ASN1ObjectIdentifier o2 = aSN1ObjectIdentifier.o("1");
        b = o2;
        ASN1ObjectIdentifier o3 = o2.o("1");
        c = o3;
        d = o2.o(ExifInterface.GPS_MEASUREMENT_2D);
        e = o2.o("0");
        f = o2.o("1");
        g = o3.o("1");
        h = o3.o(ExifInterface.GPS_MEASUREMENT_2D);
        i = o3.o(ExifInterface.GPS_MEASUREMENT_3D);
        j = o3.o("4");
        k = o3.o("5");
        l = o3.o("6");
        m = o3.o("7");
        n = o3.o("8");
        o = o3.o(DbParams.GZIP_DATA_ENCRYPT);
        p = o3.o("10");
        q = o3.o("11");
        r = o3.o("12");
        s = o3.o("13");
        t = o3.o("14");
        u = o3.o("15");
        v = o3.o("21");
        w = o3.o("22");
        x = o3.o("23");
        y = o3.o("31");
        z = o3.o("32");
        A = o3.o("33");
        B = o3.o("34");
        C = o3.o("35");
        D = o3.o("36");
        E = o3.o("37");
        F = o3.o("38");
        G = o3.o("39");
        H = o3.o("40");
        I = o3.o("41");
        J = o3.o(RoomMasterTable.DEFAULT_ID);
        K = o3.o("43");
        L = o3.o("44");
        M = o3.o("45");
    }
}
