package org.spongycastle.asn1.x9;

import androidx.exifinterface.media.ExifInterface;
import com.sensorsdata.analytics.android.sdk.data.adapter.DbParams;
import org.spongycastle.asn1.ASN1ObjectIdentifier;

public interface X9ObjectIdentifiers {
    public static final ASN1ObjectIdentifier A3;
    public static final ASN1ObjectIdentifier B3;
    public static final ASN1ObjectIdentifier C3;
    public static final ASN1ObjectIdentifier D3;
    public static final ASN1ObjectIdentifier E3;
    public static final ASN1ObjectIdentifier F3;
    public static final ASN1ObjectIdentifier G3;
    public static final ASN1ObjectIdentifier H3;
    public static final ASN1ObjectIdentifier I3;
    public static final ASN1ObjectIdentifier J3;
    public static final ASN1ObjectIdentifier K3;
    public static final ASN1ObjectIdentifier L3;
    public static final ASN1ObjectIdentifier M3;
    public static final ASN1ObjectIdentifier N3;
    public static final ASN1ObjectIdentifier O3;
    public static final ASN1ObjectIdentifier P3;
    public static final ASN1ObjectIdentifier Q3;
    public static final ASN1ObjectIdentifier R3;
    public static final ASN1ObjectIdentifier S3;
    public static final ASN1ObjectIdentifier T3;
    public static final ASN1ObjectIdentifier U3;
    public static final ASN1ObjectIdentifier V3;
    public static final ASN1ObjectIdentifier W3;
    public static final ASN1ObjectIdentifier X3;
    public static final ASN1ObjectIdentifier Y3;
    public static final ASN1ObjectIdentifier Z3;
    public static final ASN1ObjectIdentifier a4;
    public static final ASN1ObjectIdentifier b4;
    public static final ASN1ObjectIdentifier c4;
    public static final ASN1ObjectIdentifier d4 = new ASN1ObjectIdentifier("1.2.840.10040.4.1");
    public static final ASN1ObjectIdentifier e4 = new ASN1ObjectIdentifier("1.2.840.10040.4.3");
    public static final ASN1ObjectIdentifier f4;
    public static final ASN1ObjectIdentifier g4;
    public static final ASN1ObjectIdentifier h4;
    public static final ASN1ObjectIdentifier i3;
    public static final ASN1ObjectIdentifier i4;
    public static final ASN1ObjectIdentifier j3;
    public static final ASN1ObjectIdentifier j4;
    public static final ASN1ObjectIdentifier k3;
    public static final ASN1ObjectIdentifier k4;
    public static final ASN1ObjectIdentifier l3;
    public static final ASN1ObjectIdentifier l4;
    public static final ASN1ObjectIdentifier m3;
    public static final ASN1ObjectIdentifier m4;
    public static final ASN1ObjectIdentifier n3;
    public static final ASN1ObjectIdentifier n4;
    public static final ASN1ObjectIdentifier o3;
    public static final ASN1ObjectIdentifier o4;
    public static final ASN1ObjectIdentifier q3;
    public static final ASN1ObjectIdentifier q4;
    public static final ASN1ObjectIdentifier r3;
    public static final ASN1ObjectIdentifier r4;
    public static final ASN1ObjectIdentifier s3;
    public static final ASN1ObjectIdentifier s4;
    public static final ASN1ObjectIdentifier t3;
    public static final ASN1ObjectIdentifier t4;
    public static final ASN1ObjectIdentifier u3;
    public static final ASN1ObjectIdentifier u4;
    public static final ASN1ObjectIdentifier v3;
    public static final ASN1ObjectIdentifier v4;
    public static final ASN1ObjectIdentifier w3;
    public static final ASN1ObjectIdentifier w4;
    public static final ASN1ObjectIdentifier x3;
    public static final ASN1ObjectIdentifier x4;
    public static final ASN1ObjectIdentifier y3;
    public static final ASN1ObjectIdentifier y4;
    public static final ASN1ObjectIdentifier z3;

    static {
        ASN1ObjectIdentifier aSN1ObjectIdentifier = new ASN1ObjectIdentifier("1.2.840.10045");
        i3 = aSN1ObjectIdentifier;
        ASN1ObjectIdentifier o = aSN1ObjectIdentifier.o("1");
        j3 = o;
        k3 = o.o("1");
        ASN1ObjectIdentifier o2 = o.o(ExifInterface.GPS_MEASUREMENT_2D);
        l3 = o2;
        m3 = o2.o("3.1");
        n3 = o2.o("3.2");
        o3 = o2.o("3.3");
        ASN1ObjectIdentifier o5 = aSN1ObjectIdentifier.o("4");
        q3 = o5;
        r3 = o5.o("1");
        ASN1ObjectIdentifier o6 = aSN1ObjectIdentifier.o(ExifInterface.GPS_MEASUREMENT_2D);
        s3 = o6;
        t3 = o6.o("1");
        ASN1ObjectIdentifier o7 = o5.o(ExifInterface.GPS_MEASUREMENT_3D);
        u3 = o7;
        v3 = o7.o("1");
        w3 = o7.o(ExifInterface.GPS_MEASUREMENT_2D);
        x3 = o7.o(ExifInterface.GPS_MEASUREMENT_3D);
        y3 = o7.o("4");
        ASN1ObjectIdentifier o8 = aSN1ObjectIdentifier.o(ExifInterface.GPS_MEASUREMENT_3D);
        z3 = o8;
        ASN1ObjectIdentifier o9 = o8.o("0");
        A3 = o9;
        B3 = o9.o("1");
        C3 = o9.o(ExifInterface.GPS_MEASUREMENT_2D);
        D3 = o9.o(ExifInterface.GPS_MEASUREMENT_3D);
        E3 = o9.o("4");
        F3 = o9.o("5");
        G3 = o9.o("6");
        H3 = o9.o("7");
        I3 = o9.o("8");
        J3 = o9.o(DbParams.GZIP_DATA_ENCRYPT);
        K3 = o9.o("10");
        L3 = o9.o("11");
        M3 = o9.o("12");
        N3 = o9.o("13");
        O3 = o9.o("14");
        P3 = o9.o("15");
        Q3 = o9.o("16");
        R3 = o9.o("17");
        S3 = o9.o("18");
        T3 = o9.o("19");
        U3 = o9.o("20");
        ASN1ObjectIdentifier o10 = o8.o("1");
        V3 = o10;
        W3 = o10.o("1");
        X3 = o10.o(ExifInterface.GPS_MEASUREMENT_2D);
        Y3 = o10.o(ExifInterface.GPS_MEASUREMENT_3D);
        Z3 = o10.o("4");
        a4 = o10.o("5");
        b4 = o10.o("6");
        c4 = o10.o("7");
        ASN1ObjectIdentifier aSN1ObjectIdentifier2 = new ASN1ObjectIdentifier("1.3.133.16.840.63.0");
        f4 = aSN1ObjectIdentifier2;
        g4 = aSN1ObjectIdentifier2.o(ExifInterface.GPS_MEASUREMENT_2D);
        h4 = aSN1ObjectIdentifier2.o(ExifInterface.GPS_MEASUREMENT_3D);
        i4 = aSN1ObjectIdentifier2.o("16");
        ASN1ObjectIdentifier aSN1ObjectIdentifier3 = new ASN1ObjectIdentifier("1.2.840.10046");
        j4 = aSN1ObjectIdentifier3;
        k4 = aSN1ObjectIdentifier3.o("2.1");
        ASN1ObjectIdentifier o11 = aSN1ObjectIdentifier3.o(ExifInterface.GPS_MEASUREMENT_3D);
        l4 = o11;
        m4 = o11.o("1");
        n4 = o11.o(ExifInterface.GPS_MEASUREMENT_2D);
        o4 = o11.o(ExifInterface.GPS_MEASUREMENT_3D);
        q4 = o11.o("4");
        r4 = o11.o("5");
        s4 = o11.o("6");
        t4 = o11.o("7");
        u4 = o11.o("8");
        ASN1ObjectIdentifier aSN1ObjectIdentifier4 = new ASN1ObjectIdentifier("1.3.133.16.840.9.44");
        v4 = aSN1ObjectIdentifier4;
        ASN1ObjectIdentifier o12 = aSN1ObjectIdentifier4.o("1");
        w4 = o12;
        x4 = o12.o("1");
        y4 = o12.o(ExifInterface.GPS_MEASUREMENT_2D);
    }
}
