package org.spongycastle.asn1.sec;

import androidx.exifinterface.media.ExifInterface;
import com.sensorsdata.analytics.android.sdk.data.adapter.DbParams;
import org.spongycastle.asn1.ASN1ObjectIdentifier;
import org.spongycastle.asn1.x9.X9ObjectIdentifiers;

public interface SECObjectIdentifiers {
    public static final ASN1ObjectIdentifier A;
    public static final ASN1ObjectIdentifier B;
    public static final ASN1ObjectIdentifier C;
    public static final ASN1ObjectIdentifier D;
    public static final ASN1ObjectIdentifier E;
    public static final ASN1ObjectIdentifier F;
    public static final ASN1ObjectIdentifier G = X9ObjectIdentifiers.W3;
    public static final ASN1ObjectIdentifier H = X9ObjectIdentifiers.c4;
    public static final ASN1ObjectIdentifier I;
    public static final ASN1ObjectIdentifier J;
    public static final ASN1ObjectIdentifier K;
    public static final ASN1ObjectIdentifier L;
    public static final ASN1ObjectIdentifier M;
    public static final ASN1ObjectIdentifier N;
    public static final ASN1ObjectIdentifier O;
    public static final ASN1ObjectIdentifier P;
    public static final ASN1ObjectIdentifier Q;
    public static final ASN1ObjectIdentifier R;
    public static final ASN1ObjectIdentifier S;
    public static final ASN1ObjectIdentifier T;
    public static final ASN1ObjectIdentifier U;
    public static final ASN1ObjectIdentifier V;
    public static final ASN1ObjectIdentifier W;
    public static final ASN1ObjectIdentifier X;
    public static final ASN1ObjectIdentifier Y;
    public static final ASN1ObjectIdentifier a;
    public static final ASN1ObjectIdentifier b;
    public static final ASN1ObjectIdentifier c;
    public static final ASN1ObjectIdentifier d;
    public static final ASN1ObjectIdentifier e;
    public static final ASN1ObjectIdentifier f;
    public static final ASN1ObjectIdentifier g;
    public static final ASN1ObjectIdentifier h;
    public static final ASN1ObjectIdentifier i;
    public static final ASN1ObjectIdentifier j;
    public static final ASN1ObjectIdentifier k;
    public static final ASN1ObjectIdentifier l;
    public static final ASN1ObjectIdentifier m;
    public static final ASN1ObjectIdentifier n;
    public static final ASN1ObjectIdentifier o;
    public static final ASN1ObjectIdentifier p;
    public static final ASN1ObjectIdentifier q;
    public static final ASN1ObjectIdentifier r;
    public static final ASN1ObjectIdentifier s;
    public static final ASN1ObjectIdentifier t;
    public static final ASN1ObjectIdentifier u;
    public static final ASN1ObjectIdentifier v;
    public static final ASN1ObjectIdentifier w;
    public static final ASN1ObjectIdentifier x;
    public static final ASN1ObjectIdentifier y;
    public static final ASN1ObjectIdentifier z;

    static {
        ASN1ObjectIdentifier aSN1ObjectIdentifier = new ASN1ObjectIdentifier("1.3.132.0");
        a = aSN1ObjectIdentifier;
        b = aSN1ObjectIdentifier.o("1");
        c = aSN1ObjectIdentifier.o(ExifInterface.GPS_MEASUREMENT_2D);
        d = aSN1ObjectIdentifier.o(ExifInterface.GPS_MEASUREMENT_3D);
        e = aSN1ObjectIdentifier.o("4");
        f = aSN1ObjectIdentifier.o("5");
        g = aSN1ObjectIdentifier.o("6");
        h = aSN1ObjectIdentifier.o("7");
        i = aSN1ObjectIdentifier.o("8");
        j = aSN1ObjectIdentifier.o(DbParams.GZIP_DATA_ENCRYPT);
        k = aSN1ObjectIdentifier.o("10");
        l = aSN1ObjectIdentifier.o("15");
        m = aSN1ObjectIdentifier.o("16");
        n = aSN1ObjectIdentifier.o("17");
        o = aSN1ObjectIdentifier.o("22");
        p = aSN1ObjectIdentifier.o("23");
        q = aSN1ObjectIdentifier.o("24");
        r = aSN1ObjectIdentifier.o("25");
        s = aSN1ObjectIdentifier.o("26");
        t = aSN1ObjectIdentifier.o("27");
        u = aSN1ObjectIdentifier.o("28");
        v = aSN1ObjectIdentifier.o("29");
        w = aSN1ObjectIdentifier.o("30");
        x = aSN1ObjectIdentifier.o("31");
        y = aSN1ObjectIdentifier.o("32");
        z = aSN1ObjectIdentifier.o("33");
        A = aSN1ObjectIdentifier.o("34");
        B = aSN1ObjectIdentifier.o("35");
        C = aSN1ObjectIdentifier.o("36");
        D = aSN1ObjectIdentifier.o("37");
        E = aSN1ObjectIdentifier.o("38");
        F = aSN1ObjectIdentifier.o("39");
        ASN1ObjectIdentifier aSN1ObjectIdentifier2 = new ASN1ObjectIdentifier("1.3.132.1");
        I = aSN1ObjectIdentifier2;
        J = aSN1ObjectIdentifier2.o("11.0");
        K = aSN1ObjectIdentifier2.o("11.1");
        L = aSN1ObjectIdentifier2.o("11.2");
        M = aSN1ObjectIdentifier2.o("11.3");
        N = aSN1ObjectIdentifier2.o("14.0");
        O = aSN1ObjectIdentifier2.o("14.1");
        P = aSN1ObjectIdentifier2.o("14.2");
        Q = aSN1ObjectIdentifier2.o("14.3");
        R = aSN1ObjectIdentifier2.o("15.0");
        S = aSN1ObjectIdentifier2.o("15.1");
        T = aSN1ObjectIdentifier2.o("15.2");
        U = aSN1ObjectIdentifier2.o("15.3");
        V = aSN1ObjectIdentifier2.o("16.0");
        W = aSN1ObjectIdentifier2.o("16.1");
        X = aSN1ObjectIdentifier2.o("16.2");
        Y = aSN1ObjectIdentifier2.o("16.3");
    }
}
