package org.spongycastle.asn1.pkcs;

import androidx.exifinterface.media.ExifInterface;
import com.sensorsdata.analytics.android.sdk.data.adapter.DbParams;
import org.spongycastle.asn1.ASN1ObjectIdentifier;

public interface PKCSObjectIdentifiers {
    public static final ASN1ObjectIdentifier A0 = new ASN1ObjectIdentifier("1.2.840.113549.1.7.1").v();
    public static final ASN1ObjectIdentifier A1;
    public static final ASN1ObjectIdentifier A2 = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.3.5");
    public static final ASN1ObjectIdentifier B0 = new ASN1ObjectIdentifier("1.2.840.113549.1.7.2").v();
    public static final ASN1ObjectIdentifier B1;
    public static final ASN1ObjectIdentifier B2 = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.3.10");
    public static final ASN1ObjectIdentifier C0 = new ASN1ObjectIdentifier("1.2.840.113549.1.7.3").v();
    public static final ASN1ObjectIdentifier C1;
    public static final ASN1ObjectIdentifier D0 = new ASN1ObjectIdentifier("1.2.840.113549.1.7.4").v();
    public static final ASN1ObjectIdentifier D1;
    public static final ASN1ObjectIdentifier E0 = new ASN1ObjectIdentifier("1.2.840.113549.1.7.5").v();
    public static final ASN1ObjectIdentifier E1;
    public static final ASN1ObjectIdentifier F0 = new ASN1ObjectIdentifier("1.2.840.113549.1.7.6").v();
    public static final ASN1ObjectIdentifier F1;
    public static final ASN1ObjectIdentifier G0;
    public static final ASN1ObjectIdentifier G1;
    public static final ASN1ObjectIdentifier H0;
    public static final ASN1ObjectIdentifier H1;
    public static final ASN1ObjectIdentifier I0;
    public static final ASN1ObjectIdentifier I1;
    public static final ASN1ObjectIdentifier J;
    public static final ASN1ObjectIdentifier J0;
    public static final ASN1ObjectIdentifier J1;
    public static final ASN1ObjectIdentifier K;
    public static final ASN1ObjectIdentifier K0;
    public static final ASN1ObjectIdentifier K1;
    public static final ASN1ObjectIdentifier L;
    public static final ASN1ObjectIdentifier L0;
    public static final ASN1ObjectIdentifier L1;
    public static final ASN1ObjectIdentifier M;
    public static final ASN1ObjectIdentifier M0;
    public static final ASN1ObjectIdentifier M1;
    public static final ASN1ObjectIdentifier N;
    public static final ASN1ObjectIdentifier N0;
    public static final ASN1ObjectIdentifier N1;
    public static final ASN1ObjectIdentifier O;
    public static final ASN1ObjectIdentifier O0;
    public static final ASN1ObjectIdentifier O1;
    public static final ASN1ObjectIdentifier P;
    public static final ASN1ObjectIdentifier P0;
    public static final ASN1ObjectIdentifier P1;
    public static final ASN1ObjectIdentifier Q;
    public static final ASN1ObjectIdentifier Q0;
    public static final ASN1ObjectIdentifier Q1;
    public static final ASN1ObjectIdentifier R;
    public static final ASN1ObjectIdentifier R0;
    public static final ASN1ObjectIdentifier R1;
    public static final ASN1ObjectIdentifier S;
    public static final ASN1ObjectIdentifier S0;
    public static final ASN1ObjectIdentifier S1;
    public static final ASN1ObjectIdentifier T;
    public static final ASN1ObjectIdentifier T0;
    public static final ASN1ObjectIdentifier T1;
    public static final ASN1ObjectIdentifier U;
    public static final ASN1ObjectIdentifier U0;
    public static final ASN1ObjectIdentifier U1;
    public static final ASN1ObjectIdentifier V;
    public static final ASN1ObjectIdentifier V0;
    public static final ASN1ObjectIdentifier V1;
    public static final ASN1ObjectIdentifier W;
    public static final ASN1ObjectIdentifier W0;
    public static final ASN1ObjectIdentifier W1;
    public static final ASN1ObjectIdentifier X;
    public static final ASN1ObjectIdentifier X0;
    public static final ASN1ObjectIdentifier X1;
    public static final ASN1ObjectIdentifier Y;
    public static final ASN1ObjectIdentifier Y0;
    public static final ASN1ObjectIdentifier Y1;
    public static final ASN1ObjectIdentifier Z;
    public static final ASN1ObjectIdentifier Z0;
    public static final ASN1ObjectIdentifier Z1;
    public static final ASN1ObjectIdentifier a0;
    public static final ASN1ObjectIdentifier b0;
    public static final ASN1ObjectIdentifier b1;
    public static final ASN1ObjectIdentifier b2;
    public static final ASN1ObjectIdentifier c0;
    public static final ASN1ObjectIdentifier c1;
    public static final ASN1ObjectIdentifier c2;
    public static final ASN1ObjectIdentifier d0;
    public static final ASN1ObjectIdentifier d1;
    public static final ASN1ObjectIdentifier d2;
    public static final ASN1ObjectIdentifier e0;
    public static final ASN1ObjectIdentifier e1;
    public static final ASN1ObjectIdentifier e2;
    public static final ASN1ObjectIdentifier f0;
    public static final ASN1ObjectIdentifier f1;
    public static final ASN1ObjectIdentifier f2 = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.5.1");
    public static final ASN1ObjectIdentifier g0;
    public static final ASN1ObjectIdentifier g1;
    public static final ASN1ObjectIdentifier g2 = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.5.2");
    public static final ASN1ObjectIdentifier h0;
    public static final ASN1ObjectIdentifier h1;
    public static final ASN1ObjectIdentifier h2;
    public static final ASN1ObjectIdentifier i0;
    public static final ASN1ObjectIdentifier i1;
    public static final ASN1ObjectIdentifier i2;
    public static final ASN1ObjectIdentifier j0;
    public static final ASN1ObjectIdentifier j1;
    public static final ASN1ObjectIdentifier j2;
    public static final ASN1ObjectIdentifier k0;
    public static final ASN1ObjectIdentifier k1;
    public static final ASN1ObjectIdentifier k2;
    public static final ASN1ObjectIdentifier l0;
    public static final ASN1ObjectIdentifier l1;
    public static final ASN1ObjectIdentifier l2;
    public static final ASN1ObjectIdentifier m0;
    public static final ASN1ObjectIdentifier m1;
    public static final ASN1ObjectIdentifier m2;
    public static final ASN1ObjectIdentifier n0;
    public static final ASN1ObjectIdentifier n1;
    public static final ASN1ObjectIdentifier n2;
    public static final ASN1ObjectIdentifier o0;
    public static final ASN1ObjectIdentifier o1;
    public static final ASN1ObjectIdentifier o2;
    public static final ASN1ObjectIdentifier q0;
    public static final ASN1ObjectIdentifier q1;
    public static final ASN1ObjectIdentifier q2;
    public static final ASN1ObjectIdentifier r0;
    public static final ASN1ObjectIdentifier r1;
    public static final ASN1ObjectIdentifier r2;
    public static final ASN1ObjectIdentifier s0;
    public static final ASN1ObjectIdentifier s1;
    public static final ASN1ObjectIdentifier s2;
    public static final ASN1ObjectIdentifier t0;
    public static final ASN1ObjectIdentifier t1;
    public static final ASN1ObjectIdentifier t2;
    public static final ASN1ObjectIdentifier u0;
    public static final ASN1ObjectIdentifier u1;
    public static final ASN1ObjectIdentifier u2;
    public static final ASN1ObjectIdentifier v0;
    public static final ASN1ObjectIdentifier v1;
    public static final ASN1ObjectIdentifier v2;
    public static final ASN1ObjectIdentifier w0;
    public static final ASN1ObjectIdentifier w1;
    public static final ASN1ObjectIdentifier w2;
    public static final ASN1ObjectIdentifier x0;
    public static final ASN1ObjectIdentifier x1;
    public static final ASN1ObjectIdentifier x2;
    public static final ASN1ObjectIdentifier y0;
    public static final ASN1ObjectIdentifier y1;
    public static final ASN1ObjectIdentifier y2 = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.3.6");
    public static final ASN1ObjectIdentifier z0 = new ASN1ObjectIdentifier("1.2.840.113549.1.7").v();
    public static final ASN1ObjectIdentifier z1;
    public static final ASN1ObjectIdentifier z2 = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.3.7");

    static {
        ASN1ObjectIdentifier aSN1ObjectIdentifier = new ASN1ObjectIdentifier("1.2.840.113549.1.1");
        J = aSN1ObjectIdentifier;
        K = aSN1ObjectIdentifier.o("1");
        L = aSN1ObjectIdentifier.o(ExifInterface.GPS_MEASUREMENT_2D);
        M = aSN1ObjectIdentifier.o(ExifInterface.GPS_MEASUREMENT_3D);
        N = aSN1ObjectIdentifier.o("4");
        O = aSN1ObjectIdentifier.o("5");
        P = aSN1ObjectIdentifier.o("6");
        Q = aSN1ObjectIdentifier.o("7");
        R = aSN1ObjectIdentifier.o("8");
        S = aSN1ObjectIdentifier.o(DbParams.GZIP_DATA_ENCRYPT);
        T = aSN1ObjectIdentifier.o("10");
        U = aSN1ObjectIdentifier.o("11");
        V = aSN1ObjectIdentifier.o("12");
        W = aSN1ObjectIdentifier.o("13");
        X = aSN1ObjectIdentifier.o("14");
        Y = aSN1ObjectIdentifier.o("15");
        Z = aSN1ObjectIdentifier.o("16");
        String str = "16";
        ASN1ObjectIdentifier aSN1ObjectIdentifier2 = new ASN1ObjectIdentifier("1.2.840.113549.1.3");
        a0 = aSN1ObjectIdentifier2;
        b0 = aSN1ObjectIdentifier2.o("1");
        ASN1ObjectIdentifier aSN1ObjectIdentifier3 = new ASN1ObjectIdentifier("1.2.840.113549.1.5");
        c0 = aSN1ObjectIdentifier3;
        d0 = aSN1ObjectIdentifier3.o("1");
        e0 = aSN1ObjectIdentifier3.o("4");
        f0 = aSN1ObjectIdentifier3.o(ExifInterface.GPS_MEASUREMENT_3D);
        g0 = aSN1ObjectIdentifier3.o("6");
        h0 = aSN1ObjectIdentifier3.o("10");
        i0 = aSN1ObjectIdentifier3.o("11");
        j0 = aSN1ObjectIdentifier3.o("13");
        k0 = aSN1ObjectIdentifier3.o("12");
        ASN1ObjectIdentifier aSN1ObjectIdentifier4 = new ASN1ObjectIdentifier("1.2.840.113549.3");
        l0 = aSN1ObjectIdentifier4;
        m0 = aSN1ObjectIdentifier4.o("7");
        n0 = aSN1ObjectIdentifier4.o(ExifInterface.GPS_MEASUREMENT_2D);
        o0 = aSN1ObjectIdentifier4.o("4");
        ASN1ObjectIdentifier aSN1ObjectIdentifier5 = new ASN1ObjectIdentifier("1.2.840.113549.2");
        q0 = aSN1ObjectIdentifier5;
        r0 = aSN1ObjectIdentifier5.o(ExifInterface.GPS_MEASUREMENT_2D);
        s0 = aSN1ObjectIdentifier5.o("4");
        t0 = aSN1ObjectIdentifier5.o("5");
        u0 = aSN1ObjectIdentifier5.o("7").v();
        v0 = aSN1ObjectIdentifier5.o("8").v();
        w0 = aSN1ObjectIdentifier5.o(DbParams.GZIP_DATA_ENCRYPT).v();
        x0 = aSN1ObjectIdentifier5.o("10").v();
        y0 = aSN1ObjectIdentifier5.o("11").v();
        ASN1ObjectIdentifier aSN1ObjectIdentifier6 = new ASN1ObjectIdentifier("1.2.840.113549.1.9");
        G0 = aSN1ObjectIdentifier6;
        H0 = aSN1ObjectIdentifier6.o("1").v();
        I0 = aSN1ObjectIdentifier6.o(ExifInterface.GPS_MEASUREMENT_2D).v();
        J0 = aSN1ObjectIdentifier6.o(ExifInterface.GPS_MEASUREMENT_3D).v();
        K0 = aSN1ObjectIdentifier6.o("4").v();
        L0 = aSN1ObjectIdentifier6.o("5").v();
        M0 = aSN1ObjectIdentifier6.o("6").v();
        N0 = aSN1ObjectIdentifier6.o("7").v();
        O0 = aSN1ObjectIdentifier6.o("8").v();
        P0 = aSN1ObjectIdentifier6.o(DbParams.GZIP_DATA_ENCRYPT).v();
        Q0 = aSN1ObjectIdentifier6.o("13").v();
        R0 = aSN1ObjectIdentifier6.o("14").v();
        String str2 = "15";
        S0 = aSN1ObjectIdentifier6.o(str2).v();
        ASN1ObjectIdentifier v = aSN1ObjectIdentifier6.o(str).v();
        T0 = v;
        U0 = aSN1ObjectIdentifier6.o("20").v();
        V0 = aSN1ObjectIdentifier6.o("21").v();
        W0 = aSN1ObjectIdentifier6.o("22.1");
        String str3 = str2;
        ASN1ObjectIdentifier o = aSN1ObjectIdentifier6.o("22");
        X0 = o;
        Y0 = o.o("1").v();
        Z0 = o.o(ExifInterface.GPS_MEASUREMENT_2D).v();
        ASN1ObjectIdentifier o3 = aSN1ObjectIdentifier6.o("23");
        b1 = o3;
        c1 = o3.o("1").v();
        d1 = aSN1ObjectIdentifier6.o("52").v();
        e1 = aSN1ObjectIdentifier6.o("15.1");
        f1 = aSN1ObjectIdentifier6.o("15.2");
        g1 = aSN1ObjectIdentifier6.o("15.3");
        ASN1ObjectIdentifier aSN1ObjectIdentifier7 = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.1");
        h1 = aSN1ObjectIdentifier7;
        i1 = aSN1ObjectIdentifier7.o(ExifInterface.GPS_MEASUREMENT_2D);
        j1 = aSN1ObjectIdentifier7.o("4");
        k1 = aSN1ObjectIdentifier7.o(DbParams.GZIP_DATA_ENCRYPT);
        l1 = aSN1ObjectIdentifier7.o("23");
        m1 = aSN1ObjectIdentifier7.o("31");
        ASN1ObjectIdentifier o4 = v.o(ExifInterface.GPS_MEASUREMENT_3D);
        n1 = o4;
        o1 = o4.o(DbParams.GZIP_DATA_ENCRYPT);
        q1 = o4.o("14");
        ASN1ObjectIdentifier aSN1ObjectIdentifier8 = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.6");
        r1 = aSN1ObjectIdentifier8;
        s1 = aSN1ObjectIdentifier8.o("1");
        t1 = aSN1ObjectIdentifier8.o(ExifInterface.GPS_MEASUREMENT_2D);
        u1 = aSN1ObjectIdentifier8.o(ExifInterface.GPS_MEASUREMENT_3D);
        v1 = aSN1ObjectIdentifier8.o("4");
        w1 = aSN1ObjectIdentifier8.o("5");
        x1 = aSN1ObjectIdentifier8.o("6");
        ASN1ObjectIdentifier aSN1ObjectIdentifier9 = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.2");
        y1 = aSN1ObjectIdentifier9;
        z1 = aSN1ObjectIdentifier9.o("1");
        A1 = aSN1ObjectIdentifier9.o("4");
        B1 = aSN1ObjectIdentifier9.o("5");
        C1 = aSN1ObjectIdentifier9.o("10");
        D1 = aSN1ObjectIdentifier9.o("11");
        E1 = aSN1ObjectIdentifier9.o("12");
        F1 = aSN1ObjectIdentifier9.o("47");
        G1 = aSN1ObjectIdentifier9.o("7");
        H1 = aSN1ObjectIdentifier9.o("14");
        ASN1ObjectIdentifier o5 = aSN1ObjectIdentifier9.o(str3);
        I1 = o5;
        ASN1ObjectIdentifier o6 = aSN1ObjectIdentifier9.o(str);
        J1 = o6;
        ASN1ObjectIdentifier o7 = aSN1ObjectIdentifier9.o("17");
        K1 = o7;
        L1 = aSN1ObjectIdentifier9.o("18");
        ASN1ObjectIdentifier o8 = aSN1ObjectIdentifier9.o("19");
        M1 = o8;
        N1 = aSN1ObjectIdentifier9.o("20");
        O1 = aSN1ObjectIdentifier9.o("21");
        P1 = aSN1ObjectIdentifier9.o("22");
        Q1 = aSN1ObjectIdentifier9.o("23");
        R1 = aSN1ObjectIdentifier9.o("24");
        S1 = aSN1ObjectIdentifier9.o("25");
        T1 = aSN1ObjectIdentifier9.o("26");
        U1 = aSN1ObjectIdentifier9.o("27");
        V1 = aSN1ObjectIdentifier9.o("37");
        W1 = aSN1ObjectIdentifier9.o("38");
        X1 = aSN1ObjectIdentifier9.o("54");
        Y1 = aSN1ObjectIdentifier9.o("43");
        Z1 = aSN1ObjectIdentifier9.o("40");
        b2 = o5;
        c2 = o6;
        d2 = o7;
        e2 = o8;
        ASN1ObjectIdentifier aSN1ObjectIdentifier10 = new ASN1ObjectIdentifier("1.2.840.113549.1.12");
        h2 = aSN1ObjectIdentifier10;
        ASN1ObjectIdentifier o9 = aSN1ObjectIdentifier10.o("10.1");
        i2 = o9;
        j2 = o9.o("1");
        k2 = o9.o(ExifInterface.GPS_MEASUREMENT_2D);
        l2 = o9.o(ExifInterface.GPS_MEASUREMENT_3D);
        m2 = o9.o("4");
        n2 = o9.o("5");
        o2 = o9.o("6");
        ASN1ObjectIdentifier o10 = aSN1ObjectIdentifier10.o("1");
        q2 = o10;
        r2 = o10.o("1");
        s2 = o10.o(ExifInterface.GPS_MEASUREMENT_2D);
        t2 = o10.o(ExifInterface.GPS_MEASUREMENT_3D);
        u2 = o10.o("4");
        v2 = o10.o("5");
        w2 = o10.o("6");
        x2 = o10.o("6");
    }
}
