package kotlin.reflect.jvm.internal.impl.serialization.deserialization;

import kotlin.reflect.jvm.internal.impl.descriptors.b;
import kotlin.reflect.jvm.internal.impl.descriptors.f;
import kotlin.reflect.jvm.internal.impl.descriptors.w;
import kotlin.reflect.jvm.internal.impl.metadata.c;
import kotlin.reflect.jvm.internal.impl.metadata.j;
import kotlin.reflect.jvm.internal.impl.metadata.k;
import kotlin.reflect.jvm.internal.impl.metadata.q;
import kotlin.reflect.jvm.internal.impl.metadata.s;
import kotlin.reflect.jvm.internal.impl.metadata.x;

public final /* synthetic */ class b0 {
    public static final /* synthetic */ int[] a;
    public static final /* synthetic */ int[] b;
    public static final /* synthetic */ int[] c;
    public static final /* synthetic */ int[] d;
    public static final /* synthetic */ int[] e;
    public static final /* synthetic */ int[] f;
    public static final /* synthetic */ int[] g;
    public static final /* synthetic */ int[] h;
    public static final /* synthetic */ int[] i;

    static {
        int[] iArr = new int[j.values().length];
        a = iArr;
        iArr[j.DECLARATION.ordinal()] = 1;
        iArr[j.FAKE_OVERRIDE.ordinal()] = 2;
        iArr[j.DELEGATION.ordinal()] = 3;
        iArr[j.SYNTHESIZED.ordinal()] = 4;
        int[] iArr2 = new int[b.a.values().length];
        b = iArr2;
        iArr2[b.a.DECLARATION.ordinal()] = 1;
        iArr2[b.a.FAKE_OVERRIDE.ordinal()] = 2;
        iArr2[b.a.DELEGATION.ordinal()] = 3;
        iArr2[b.a.SYNTHESIZED.ordinal()] = 4;
        int[] iArr3 = new int[k.values().length];
        c = iArr3;
        iArr3[k.FINAL.ordinal()] = 1;
        iArr3[k.OPEN.ordinal()] = 2;
        iArr3[k.ABSTRACT.ordinal()] = 3;
        iArr3[k.SEALED.ordinal()] = 4;
        int[] iArr4 = new int[w.values().length];
        d = iArr4;
        iArr4[w.FINAL.ordinal()] = 1;
        iArr4[w.OPEN.ordinal()] = 2;
        iArr4[w.ABSTRACT.ordinal()] = 3;
        iArr4[w.SEALED.ordinal()] = 4;
        int[] iArr5 = new int[x.values().length];
        e = iArr5;
        iArr5[x.INTERNAL.ordinal()] = 1;
        iArr5[x.PRIVATE.ordinal()] = 2;
        iArr5[x.PRIVATE_TO_THIS.ordinal()] = 3;
        iArr5[x.PROTECTED.ordinal()] = 4;
        iArr5[x.PUBLIC.ordinal()] = 5;
        iArr5[x.LOCAL.ordinal()] = 6;
        int[] iArr6 = new int[c.C0384c.values().length];
        f = iArr6;
        iArr6[c.C0384c.CLASS.ordinal()] = 1;
        iArr6[c.C0384c.INTERFACE.ordinal()] = 2;
        iArr6[c.C0384c.ENUM_CLASS.ordinal()] = 3;
        iArr6[c.C0384c.ENUM_ENTRY.ordinal()] = 4;
        iArr6[c.C0384c.ANNOTATION_CLASS.ordinal()] = 5;
        iArr6[c.C0384c.OBJECT.ordinal()] = 6;
        iArr6[c.C0384c.COMPANION_OBJECT.ordinal()] = 7;
        int[] iArr7 = new int[f.values().length];
        g = iArr7;
        iArr7[f.CLASS.ordinal()] = 1;
        iArr7[f.INTERFACE.ordinal()] = 2;
        iArr7[f.ENUM_CLASS.ordinal()] = 3;
        iArr7[f.ENUM_ENTRY.ordinal()] = 4;
        iArr7[f.ANNOTATION_CLASS.ordinal()] = 5;
        iArr7[f.OBJECT.ordinal()] = 6;
        int[] iArr8 = new int[s.c.values().length];
        h = iArr8;
        iArr8[s.c.IN.ordinal()] = 1;
        iArr8[s.c.OUT.ordinal()] = 2;
        iArr8[s.c.INV.ordinal()] = 3;
        int[] iArr9 = new int[q.b.c.values().length];
        i = iArr9;
        iArr9[q.b.c.IN.ordinal()] = 1;
        iArr9[q.b.c.OUT.ordinal()] = 2;
        iArr9[q.b.c.INV.ordinal()] = 3;
        iArr9[q.b.c.STAR.ordinal()] = 4;
    }
}
