"""An AAC-LC track for the direct RTSP publish.

Home Assistant's stream component (its HLS player and ``camera.record``) keeps
AAC and MP3 audio and drops G.711, and the cameras send G.711 A-law. The pull
serves already encode AAC; the direct publish sent A-law only, so HLS played
it silent. Asking go2rtc to transcode is not an option: the go2rtc build these
streams are served by stamps a transcoded AAC track on a 90 kHz clock and every
HLS viewer played about eleven times too slow.

So the publish carries its own AAC track, after the A-law one, with timestamps
we own. Everything that reads the first audio track (WebRTC) is unchanged.
"""

from __future__ import annotations

import logging
import os
import struct
from typing import List, Optional

_LOGGER = logging.getLogger(__name__)

ENV_PUBLISH_AAC = "AIDOT_PUBLISH_AAC"
AAC_CLOCK_RATE = 48000
AAC_SAMPLES_PER_FRAME = 1024
AAC_BITRATE = 64000
PCMA_RATE = 8000
#: How long the camera may send no audio before silence is generated in its place.
AAC_IDLE_FILL_S = 0.5
#: The largest silence one step may insert; a larger jump re-anchors instead.
AAC_MAX_FILL_S = 5.0

_SR_INDEX = {
    96000: 0,
    88200: 1,
    64000: 2,
    48000: 3,
    44100: 4,
    32000: 5,
    24000: 6,
    22050: 7,
    16000: 8,
    12000: 9,
    11025: 10,
    8000: 11,
    7350: 12,
}
_OFF = ("0", "false", "no", "off")


def publish_aac_enabled() -> bool:
    """Whether the direct publish adds the AAC track (default on)."""
    return os.environ.get(ENV_PUBLISH_AAC, "1").strip().lower() not in _OFF


def audio_specific_config(
    sample_rate: int = AAC_CLOCK_RATE, channels: int = 1
) -> bytes:
    """ISO 14496-3 AudioSpecificConfig for AAC-LC (object type 2)."""
    return struct.pack(
        "!H", (2 << 11) | (_SR_INDEX[sample_rate] << 7) | (channels << 3)
    )


def aac_fmtp(sample_rate: int = AAC_CLOCK_RATE, channels: int = 1) -> str:
    """The ``a=fmtp`` body for an RFC 3640 AAC-hbr track."""
    return (
        "streamtype=5;profile-level-id=1;mode=AAC-hbr;"
        "sizelength=13;indexlength=3;indexdeltalength=3;"
        "config=" + audio_specific_config(sample_rate, channels).hex()
    )


def packetize_aac(frame: bytes) -> bytes:
    """One access unit as an RFC 3640 payload: AU-headers-length (bits), one header."""
    return struct.pack("!HH", 16, len(frame) << 3) + frame


#: A-law's encoding of a zero sample.
ALAW_SILENCE = b"\xd5"
_MASK = 0xFFFFFFFF


def _signed32(d: int) -> int:
    d &= _MASK
    return d - 0x100000000 if d >= 0x80000000 else d


class AacPacer:
    """Which 8 kHz samples to encode next, so AAC follows the PCMA track's clock.

    While the camera sends audio, the position follows the timestamps the
    publisher gave the PCMA track: a gap is filled with silence, an overlap is
    trimmed, and nothing ever steps backward - so AAC keeps the camera's audio
    clock, which is the same crystal as its video. When the camera sends no
    audio for ``AAC_IDLE_FILL_S`` (battery cameras send it sparsely), silence
    is generated by wall-clock time so the track never goes quiet: Home
    Assistant's stream worker drops an audio track that sends nothing early.
    """

    def __init__(self) -> None:
        self._pos: Optional[int] = None  # next PCMA timestamp expected (8 kHz)
        self._last: Optional[float] = None  # wall time the position describes
        self.silence_samples = 0
        self.trimmed_samples = 0
        self.reanchors = 0

    def feed(self, alaw: bytes, pcma_ts: int, now: float) -> List[bytes]:
        out: List[bytes] = []
        if not alaw:
            return out
        ts = pcma_ts & _MASK
        if self._pos is None:
            self._pos = ts
        d = _signed32(ts - self._pos)
        if d > AAC_MAX_FILL_S * PCMA_RATE:
            self.reanchors += 1
            _LOGGER.info(
                "AAC track: camera audio jumped %.1f s - re-anchoring", d / PCMA_RATE
            )
            self._pos = ts
        elif d > 0:
            out.append(ALAW_SILENCE * d)
            self.silence_samples += d
            self._pos = ts
        elif d < 0:
            overlap = -d
            if overlap >= len(alaw):
                self.trimmed_samples += len(alaw)
                return out
            alaw = alaw[overlap:]
            self.trimmed_samples += overlap
        out.append(alaw)
        self._pos = (self._pos + len(alaw)) & _MASK
        self._last = now
        return out

    def tick(self, now: float) -> List[bytes]:
        if self._last is None:
            self._last = now
            return []
        idle = now - self._last
        if idle < AAC_IDLE_FILL_S:
            return []
        n = round(min(idle, AAC_MAX_FILL_S) * PCMA_RATE)
        self._last += n / PCMA_RATE
        if self._pos is not None:
            self._pos = (self._pos + n) & _MASK
        self.silence_samples += n
        return [ALAW_SILENCE * n]
