package org.spongycastle.asn1.bc;

import androidx.exifinterface.media.ExifInterface;
import org.spongycastle.asn1.ASN1ObjectIdentifier;

public interface BCObjectIdentifiers {
    public static final ASN1ObjectIdentifier A;
    public static final ASN1ObjectIdentifier B;
    public static final ASN1ObjectIdentifier C;
    public static final ASN1ObjectIdentifier D;
    public static final ASN1ObjectIdentifier E;
    public static final ASN1ObjectIdentifier F;
    public static final ASN1ObjectIdentifier G;
    public static final ASN1ObjectIdentifier H;
    public static final ASN1ObjectIdentifier a;
    public static final ASN1ObjectIdentifier b;
    public static final ASN1ObjectIdentifier c;
    public static final ASN1ObjectIdentifier d;
    public static final ASN1ObjectIdentifier e;
    public static final ASN1ObjectIdentifier f;
    public static final ASN1ObjectIdentifier g;
    public static final ASN1ObjectIdentifier h;
    public static final ASN1ObjectIdentifier i;
    public static final ASN1ObjectIdentifier j;
    public static final ASN1ObjectIdentifier k;
    public static final ASN1ObjectIdentifier l;
    public static final ASN1ObjectIdentifier m;
    public static final ASN1ObjectIdentifier n;
    public static final ASN1ObjectIdentifier o;
    public static final ASN1ObjectIdentifier p;
    public static final ASN1ObjectIdentifier q;
    public static final ASN1ObjectIdentifier r;
    public static final ASN1ObjectIdentifier s;
    public static final ASN1ObjectIdentifier t;
    public static final ASN1ObjectIdentifier u;
    public static final ASN1ObjectIdentifier v;
    public static final ASN1ObjectIdentifier w;
    public static final ASN1ObjectIdentifier x;
    public static final ASN1ObjectIdentifier y;
    public static final ASN1ObjectIdentifier z;

    static {
        ASN1ObjectIdentifier aSN1ObjectIdentifier = new ASN1ObjectIdentifier("1.3.6.1.4.1.22554");
        a = aSN1ObjectIdentifier;
        ASN1ObjectIdentifier o2 = aSN1ObjectIdentifier.o("1");
        b = o2;
        ASN1ObjectIdentifier o3 = o2.o("1");
        c = o3;
        ASN1ObjectIdentifier o4 = o2.o("2.1");
        d = o4;
        e = o2.o("2.2");
        f = o2.o("2.3");
        g = o2.o("2.4");
        h = o3.o("1");
        ASN1ObjectIdentifier o5 = o3.o(ExifInterface.GPS_MEASUREMENT_2D);
        i = o5;
        j = o4.o("1");
        ASN1ObjectIdentifier o6 = o4.o(ExifInterface.GPS_MEASUREMENT_2D);
        k = o6;
        l = o5.o("1.2");
        m = o5.o("1.22");
        n = o5.o("1.42");
        o = o6.o("1.2");
        p = o6.o("1.22");
        q = o6.o("1.42");
        ASN1ObjectIdentifier o7 = aSN1ObjectIdentifier.o(ExifInterface.GPS_MEASUREMENT_2D);
        r = o7;
        ASN1ObjectIdentifier o8 = o7.o("1");
        s = o8;
        t = o8.o("1");
        u = o8.o(ExifInterface.GPS_MEASUREMENT_2D);
        v = o8.o(ExifInterface.GPS_MEASUREMENT_3D);
        ASN1ObjectIdentifier o9 = o7.o(ExifInterface.GPS_MEASUREMENT_2D);
        w = o9;
        x = o9.o("1");
        y = o9.o(ExifInterface.GPS_MEASUREMENT_2D);
        z = o9.o(ExifInterface.GPS_MEASUREMENT_3D);
        A = o9.o("4");
        ASN1ObjectIdentifier o10 = o7.o(ExifInterface.GPS_MEASUREMENT_3D);
        B = o10;
        C = o10.o("1");
        D = o10.o(ExifInterface.GPS_MEASUREMENT_2D);
        E = o10.o(ExifInterface.GPS_MEASUREMENT_3D);
        F = o10.o("4");
        ASN1ObjectIdentifier o11 = aSN1ObjectIdentifier.o(ExifInterface.GPS_MEASUREMENT_3D);
        G = o11;
        H = o11.o("1");
    }
}
