package com.amazonaws.regions;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

public class RegionDefaults {
    RegionDefaults() {
    }

    public static List<Region> getRegions() {
        List<Region> ret = new ArrayList<>();
        Region region = new Region("ap-northeast-1", "amazonaws.com");
        ret.add(region);
        updateRegion(region, ServiceAbbreviations.Autoscaling, "autoscaling.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region, "cognito-identity", "cognito-identity.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region, "cognito-idp", "cognito-idp.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region, "cognito-sync", "cognito-sync.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region, "data.iot", "data.iot.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region, ServiceAbbreviations.Dynamodb, "dynamodb.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region, ServiceAbbreviations.EC2, "ec2.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region, ServiceAbbreviations.ElasticLoadbalancing, "elasticloadbalancing.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region, "firehose", "firehose.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region, "iot", "iot.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region, "kinesis", "kinesis.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region, "kms", "kms.ap-northeast-1.amazonaws.com", false, true);
        String str = "kms";
        updateRegion(region, "lambda", "lambda.ap-northeast-1.amazonaws.com", false, true);
        String str2 = "lambda";
        updateRegion(region, "logs", "logs.ap-northeast-1.amazonaws.com", false, true);
        String str3 = "logs";
        updateRegion(region, "polly", "polly.ap-northeast-1.amazonaws.com", false, true);
        String str4 = "polly";
        updateRegion(region, ServiceAbbreviations.S3, "s3.ap-northeast-1.amazonaws.com", false, true);
        String str5 = ServiceAbbreviations.S3;
        updateRegion(region, ServiceAbbreviations.SimpleDB, "sdb.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region, ServiceAbbreviations.SNS, "sns.ap-northeast-1.amazonaws.com", false, true);
        String str6 = ServiceAbbreviations.SNS;
        updateRegion(region, ServiceAbbreviations.SQS, "sqs.ap-northeast-1.amazonaws.com", false, true);
        String str7 = ServiceAbbreviations.SQS;
        updateRegion(region, ServiceAbbreviations.STS, "sts.amazonaws.com", false, true);
        Region region2 = new Region("ap-northeast-2", "amazonaws.com");
        ret.add(region2);
        updateRegion(region2, ServiceAbbreviations.Autoscaling, "autoscaling.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region2, "cognito-identity", "cognito-identity.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region2, "cognito-idp", "cognito-idp.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region2, "cognito-sync", "cognito-sync.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region2, "data.iot", "data.iot.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region2, ServiceAbbreviations.Dynamodb, "dynamodb.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region2, ServiceAbbreviations.EC2, "ec2.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region2, ServiceAbbreviations.ElasticLoadbalancing, "elasticloadbalancing.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region2, "iot", "iot.ap-northeast-2.amazonaws.com", false, true);
        String str8 = "iot";
        String str9 = "kinesis";
        updateRegion(region2, str9, "kinesis.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region2, str, "kms.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region2, str2, "lambda.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region2, str3, "logs.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region2, str4, "polly.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region2, str5, "s3.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region2, str6, "sns.ap-northeast-2.amazonaws.com", false, true);
        String str10 = str7;
        updateRegion(region2, str10, "sqs.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region2, ServiceAbbreviations.STS, "sts.ap-northeast-2.amazonaws.com", false, true);
        Region region3 = new Region("ap-south-1", "amazonaws.com");
        ret.add(region3);
        updateRegion(region3, ServiceAbbreviations.Autoscaling, "autoscaling.ap-south-1.amazonaws.com", false, true);
        updateRegion(region3, "cognito-identity", "cognito-identity.ap-south-1.amazonaws.com", false, true);
        updateRegion(region3, "cognito-idp", "cognito-idp.ap-south-1.amazonaws.com", false, true);
        updateRegion(region3, "cognito-sync", "cognito-sync.ap-south-1.amazonaws.com", false, true);
        updateRegion(region3, ServiceAbbreviations.Dynamodb, "dynamodb.ap-south-1.amazonaws.com", false, true);
        updateRegion(region3, ServiceAbbreviations.EC2, "ec2.ap-south-1.amazonaws.com", false, true);
        updateRegion(region3, ServiceAbbreviations.ElasticLoadbalancing, "elasticloadbalancing.ap-south-1.amazonaws.com", false, true);
        updateRegion(region3, str9, "kinesis.ap-south-1.amazonaws.com", false, true);
        String str11 = str9;
        updateRegion(region3, str, "kms.ap-south-1.amazonaws.com", false, true);
        updateRegion(region3, str2, "lambda.ap-south-1.amazonaws.com", false, true);
        updateRegion(region3, str3, "logs.ap-south-1.amazonaws.com", false, true);
        updateRegion(region3, str4, "polly.ap-south-1.amazonaws.com", false, true);
        updateRegion(region3, str5, "s3.ap-south-1.amazonaws.com", false, true);
        String str12 = str6;
        updateRegion(region3, str12, "sns.ap-south-1.amazonaws.com", false, true);
        updateRegion(region3, str10, "sqs.ap-south-1.amazonaws.com", false, true);
        String str13 = "sts.amazonaws.com";
        updateRegion(region3, ServiceAbbreviations.STS, str13, false, true);
        Region region4 = new Region("ap-southeast-1", "amazonaws.com");
        ret.add(region4);
        updateRegion(region4, ServiceAbbreviations.Autoscaling, "autoscaling.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region4, "cognito-identity", "cognito-identity.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region4, "cognito-idp", "cognito-idp.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region4, "cognito-sync", "cognito-sync.ap-southeast-1.amazonaws.com", false, true);
        String str14 = "data.iot";
        updateRegion(region4, str14, "data.iot.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region4, ServiceAbbreviations.Dynamodb, "dynamodb.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region4, ServiceAbbreviations.EC2, "ec2.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region4, ServiceAbbreviations.ElasticLoadbalancing, "elasticloadbalancing.ap-southeast-1.amazonaws.com", false, true);
        String str15 = ServiceAbbreviations.ElasticLoadbalancing;
        updateRegion(region4, str8, "iot.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region4, str11, "kinesis.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region4, str, "kms.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region4, str2, "lambda.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region4, str3, "logs.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region4, str4, "polly.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region4, str5, "s3.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region4, ServiceAbbreviations.SimpleDB, "sdb.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region4, str12, "sns.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region4, str10, "sqs.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region4, ServiceAbbreviations.STS, str13, false, true);
        Region region5 = new Region("ap-southeast-2", "amazonaws.com");
        List<Region> ret2 = ret;
        ret2.add(region5);
        updateRegion(region5, ServiceAbbreviations.Autoscaling, "autoscaling.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region5, "cognito-identity", "cognito-identity.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region5, "cognito-idp", "cognito-idp.ap-southeast-2.amazonaws.com", false, true);
        String str16 = "cognito-idp";
        String str17 = "cognito-sync";
        updateRegion(region5, str17, "cognito-sync.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region5, str14, "data.iot.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region5, ServiceAbbreviations.Dynamodb, "dynamodb.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region5, ServiceAbbreviations.EC2, "ec2.ap-southeast-2.amazonaws.com", false, true);
        String str18 = str14;
        String str19 = str15;
        updateRegion(region5, str19, "elasticloadbalancing.ap-southeast-2.amazonaws.com", false, true);
        String str20 = str17;
        updateRegion(region5, str8, "iot.ap-southeast-2.amazonaws.com", false, true);
        String str21 = str11;
        updateRegion(region5, str21, "kinesis.ap-southeast-2.amazonaws.com", false, true);
        String str22 = "cognito-identity";
        updateRegion(region5, str, "kms.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region5, str2, "lambda.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region5, str3, "logs.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region5, str4, "polly.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region5, str5, "s3.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region5, ServiceAbbreviations.SimpleDB, "sdb.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region5, str12, "sns.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region5, str10, "sqs.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region5, ServiceAbbreviations.STS, str13, false, true);
        Region region6 = new Region("ca-central-1", "amazonaws.com");
        ret2.add(region6);
        updateRegion(region6, ServiceAbbreviations.Autoscaling, "autoscaling.ca-central-1.amazonaws.com", false, true);
        updateRegion(region6, ServiceAbbreviations.Dynamodb, "dynamodb.ca-central-1.amazonaws.com", false, true);
        updateRegion(region6, ServiceAbbreviations.EC2, "ec2.ca-central-1.amazonaws.com", false, true);
        updateRegion(region6, str19, "elasticloadbalancing.ca-central-1.amazonaws.com", false, true);
        updateRegion(region6, str21, "kinesis.ca-central-1.amazonaws.com", false, true);
        updateRegion(region6, str, "kms.ca-central-1.amazonaws.com", false, true);
        updateRegion(region6, str2, "lambda.ca-central-1.amazonaws.com", false, true);
        updateRegion(region6, str3, "logs.ca-central-1.amazonaws.com", false, true);
        updateRegion(region6, str4, "polly.ca-central-1.amazonaws.com", false, true);
        String str23 = str5;
        updateRegion(region6, str23, "s3.ca-central-1.amazonaws.com", false, true);
        updateRegion(region6, str12, "sns.ca-central-1.amazonaws.com", false, true);
        updateRegion(region6, str10, "sqs.ca-central-1.amazonaws.com", false, true);
        updateRegion(region6, ServiceAbbreviations.STS, str13, false, true);
        Region region7 = new Region("eu-central-1", "amazonaws.com");
        ret2.add(region7);
        updateRegion(region7, ServiceAbbreviations.Autoscaling, "autoscaling.eu-central-1.amazonaws.com", false, true);
        String str24 = ServiceAbbreviations.Autoscaling;
        updateRegion(region7, str22, "cognito-identity.eu-central-1.amazonaws.com", false, true);
        updateRegion(region7, str16, "cognito-idp.eu-central-1.amazonaws.com", false, true);
        updateRegion(region7, str20, "cognito-sync.eu-central-1.amazonaws.com", false, true);
        String str25 = str18;
        updateRegion(region7, str25, "data.iot.eu-central-1.amazonaws.com", false, true);
        updateRegion(region7, ServiceAbbreviations.Dynamodb, "dynamodb.eu-central-1.amazonaws.com", false, true);
        updateRegion(region7, ServiceAbbreviations.EC2, "ec2.eu-central-1.amazonaws.com", false, true);
        updateRegion(region7, str19, "elasticloadbalancing.eu-central-1.amazonaws.com", false, true);
        String str26 = str19;
        updateRegion(region7, "firehose", "firehose.eu-central-1.amazonaws.com", false, true);
        String str27 = str8;
        updateRegion(region7, str27, "iot.eu-central-1.amazonaws.com", false, true);
        updateRegion(region7, str21, "kinesis.eu-central-1.amazonaws.com", false, true);
        String str28 = str21;
        updateRegion(region7, str, "kms.eu-central-1.amazonaws.com", false, true);
        updateRegion(region7, str2, "lambda.eu-central-1.amazonaws.com", false, true);
        updateRegion(region7, str3, "logs.eu-central-1.amazonaws.com", false, true);
        String str29 = str4;
        updateRegion(region7, str29, "polly.eu-central-1.amazonaws.com", false, true);
        updateRegion(region7, str23, "s3.eu-central-1.amazonaws.com", false, true);
        updateRegion(region7, str12, "sns.eu-central-1.amazonaws.com", false, true);
        updateRegion(region7, str10, "sqs.eu-central-1.amazonaws.com", false, true);
        updateRegion(region7, ServiceAbbreviations.STS, str13, false, true);
        Region region8 = new Region("eu-west-1", "amazonaws.com");
        ret2.add(region8);
        List<Region> ret3 = ret2;
        updateRegion(region8, str24, "autoscaling.eu-west-1.amazonaws.com", false, true);
        updateRegion(region8, str22, "cognito-identity.eu-west-1.amazonaws.com", false, true);
        updateRegion(region8, str16, "cognito-idp.eu-west-1.amazonaws.com", false, true);
        String str30 = str20;
        updateRegion(region8, str30, "cognito-sync.eu-west-1.amazonaws.com", false, true);
        updateRegion(region8, str25, "data.iot.eu-west-1.amazonaws.com", false, true);
        updateRegion(region8, ServiceAbbreviations.Dynamodb, "dynamodb.eu-west-1.amazonaws.com", false, true);
        updateRegion(region8, ServiceAbbreviations.EC2, "ec2.eu-west-1.amazonaws.com", false, true);
        String str31 = str25;
        updateRegion(region8, str26, "elasticloadbalancing.eu-west-1.amazonaws.com", false, true);
        updateRegion(region8, "email", "email.eu-west-1.amazonaws.com", false, true);
        updateRegion(region8, "firehose", "firehose.eu-west-1.amazonaws.com", false, true);
        updateRegion(region8, str27, "iot.eu-west-1.amazonaws.com", false, true);
        updateRegion(region8, str28, "kinesis.eu-west-1.amazonaws.com", false, true);
        updateRegion(region8, str, "kms.eu-west-1.amazonaws.com", false, true);
        updateRegion(region8, str2, "lambda.eu-west-1.amazonaws.com", false, true);
        updateRegion(region8, str3, "logs.eu-west-1.amazonaws.com", false, true);
        updateRegion(region8, "machinelearning", "machinelearning.eu-west-1.amazonaws.com", false, true);
        updateRegion(region8, str29, "polly.eu-west-1.amazonaws.com", false, true);
        updateRegion(region8, "rekognition", "rekognition.eu-west-1.amazonaws.com", false, true);
        updateRegion(region8, str23, "s3.eu-west-1.amazonaws.com", false, true);
        updateRegion(region8, ServiceAbbreviations.SimpleDB, "sdb.eu-west-1.amazonaws.com", false, true);
        updateRegion(region8, str12, "sns.eu-west-1.amazonaws.com", false, true);
        updateRegion(region8, str10, "sqs.eu-west-1.amazonaws.com", false, true);
        updateRegion(region8, ServiceAbbreviations.STS, str13, false, true);
        Region region9 = new Region("eu-west-2", "amazonaws.com");
        ret3.add(region9);
        updateRegion(region9, str24, "autoscaling.eu-west-2.amazonaws.com", false, true);
        updateRegion(region9, str22, "cognito-identity.eu-west-2.amazonaws.com", false, true);
        String str32 = str16;
        updateRegion(region9, str32, "cognito-idp.eu-west-2.amazonaws.com", false, true);
        updateRegion(region9, str30, "cognito-sync.eu-west-2.amazonaws.com", false, true);
        updateRegion(region9, ServiceAbbreviations.Dynamodb, "dynamodb.eu-west-2.amazonaws.com", false, true);
        updateRegion(region9, ServiceAbbreviations.EC2, "ec2.eu-west-2.amazonaws.com", false, true);
        String str33 = str30;
        String str34 = str26;
        updateRegion(region9, str34, "elasticloadbalancing.eu-west-2.amazonaws.com", false, true);
        updateRegion(region9, str27, "iot.eu-west-2.amazonaws.com", false, true);
        String str35 = str27;
        String str36 = str28;
        updateRegion(region9, str36, "kinesis.eu-west-2.amazonaws.com", false, true);
        String str37 = str32;
        updateRegion(region9, str, "kms.eu-west-2.amazonaws.com", false, true);
        updateRegion(region9, str2, "lambda.eu-west-2.amazonaws.com", false, true);
        String str38 = str3;
        updateRegion(region9, str38, "logs.eu-west-2.amazonaws.com", false, true);
        updateRegion(region9, str29, "polly.eu-west-2.amazonaws.com", false, true);
        updateRegion(region9, str23, "s3.eu-west-2.amazonaws.com", false, true);
        updateRegion(region9, str12, "sns.eu-west-2.amazonaws.com", false, true);
        updateRegion(region9, str10, "sqs.eu-west-2.amazonaws.com", false, true);
        updateRegion(region9, ServiceAbbreviations.STS, str13, false, true);
        Region region10 = new Region("eu-west-3", "amazonaws.com");
        ret3.add(region10);
        String str39 = "amazonaws.com";
        String str40 = str24;
        updateRegion(region10, str40, "autoscaling.eu-west-3.amazonaws.com", false, true);
        updateRegion(region10, ServiceAbbreviations.Dynamodb, "dynamodb.eu-west-3.amazonaws.com", false, true);
        updateRegion(region10, ServiceAbbreviations.EC2, "ec2.eu-west-3.amazonaws.com", false, true);
        updateRegion(region10, str34, "elasticloadbalancing.eu-west-3.amazonaws.com", false, true);
        updateRegion(region10, str36, "kinesis.eu-west-3.amazonaws.com", false, true);
        String str41 = str36;
        updateRegion(region10, str, "kms.eu-west-3.amazonaws.com", false, true);
        String str42 = str2;
        updateRegion(region10, str42, "lambda.eu-west-3.amazonaws.com", false, true);
        updateRegion(region10, str38, "logs.eu-west-3.amazonaws.com", false, true);
        updateRegion(region10, str29, "polly.eu-west-3.amazonaws.com", false, true);
        updateRegion(region10, str23, "s3.eu-west-3.amazonaws.com", false, true);
        updateRegion(region10, str12, "sns.eu-west-3.amazonaws.com", false, true);
        updateRegion(region10, str10, "sqs.eu-west-3.amazonaws.com", false, true);
        updateRegion(region10, ServiceAbbreviations.STS, str13, false, true);
        Region region11 = new Region("sa-east-1", str39);
        ret3.add(region11);
        updateRegion(region11, str40, "autoscaling.sa-east-1.amazonaws.com", false, true);
        updateRegion(region11, ServiceAbbreviations.Dynamodb, "dynamodb.sa-east-1.amazonaws.com", false, true);
        updateRegion(region11, ServiceAbbreviations.EC2, "ec2.sa-east-1.amazonaws.com", false, true);
        updateRegion(region11, str34, "elasticloadbalancing.sa-east-1.amazonaws.com", false, true);
        String str43 = str34;
        updateRegion(region11, str41, "kinesis.sa-east-1.amazonaws.com", false, true);
        String str44 = str;
        updateRegion(region11, str44, "kms.sa-east-1.amazonaws.com", false, true);
        updateRegion(region11, str42, "lambda.sa-east-1.amazonaws.com", false, true);
        updateRegion(region11, str38, "logs.sa-east-1.amazonaws.com", false, true);
        updateRegion(region11, str29, "polly.sa-east-1.amazonaws.com", false, true);
        updateRegion(region11, str23, "s3.sa-east-1.amazonaws.com", false, true);
        String str45 = str23;
        updateRegion(region11, ServiceAbbreviations.SimpleDB, "sdb.sa-east-1.amazonaws.com", false, true);
        updateRegion(region11, str12, "sns.sa-east-1.amazonaws.com", false, true);
        updateRegion(region11, str10, "sqs.sa-east-1.amazonaws.com", false, true);
        updateRegion(region11, ServiceAbbreviations.STS, str13, false, true);
        String str46 = str39;
        Region region12 = new Region("us-east-1", str46);
        ret3.add(region12);
        updateRegion(region12, str40, "autoscaling.us-east-1.amazonaws.com", false, true);
        String str47 = str40;
        updateRegion(region12, str22, "cognito-identity.us-east-1.amazonaws.com", false, true);
        updateRegion(region12, str37, "cognito-idp.us-east-1.amazonaws.com", false, true);
        updateRegion(region12, str33, "cognito-sync.us-east-1.amazonaws.com", false, true);
        updateRegion(region12, str31, "data.iot.us-east-1.amazonaws.com", false, true);
        updateRegion(region12, ServiceAbbreviations.Dynamodb, "dynamodb.us-east-1.amazonaws.com", false, true);
        updateRegion(region12, ServiceAbbreviations.EC2, "ec2.us-east-1.amazonaws.com", false, true);
        updateRegion(region12, str43, "elasticloadbalancing.us-east-1.amazonaws.com", false, true);
        updateRegion(region12, "email", "email.us-east-1.amazonaws.com", false, true);
        updateRegion(region12, "firehose", "firehose.us-east-1.amazonaws.com", false, true);
        updateRegion(region12, str35, "iot.us-east-1.amazonaws.com", false, true);
        String str48 = str41;
        updateRegion(region12, str48, "kinesis.us-east-1.amazonaws.com", false, true);
        updateRegion(region12, str44, "kms.us-east-1.amazonaws.com", false, true);
        updateRegion(region12, str42, "lambda.us-east-1.amazonaws.com", false, true);
        updateRegion(region12, str38, "logs.us-east-1.amazonaws.com", false, true);
        updateRegion(region12, "machinelearning", "machinelearning.us-east-1.amazonaws.com", false, true);
        updateRegion(region12, "mobileanalytics", "mobileanalytics.us-east-1.amazonaws.com", false, true);
        updateRegion(region12, "pinpoint", "pinpoint.us-east-1.amazonaws.com", false, true);
        updateRegion(region12, str29, "polly.us-east-1.amazonaws.com", false, true);
        updateRegion(region12, "rekognition", "rekognition.us-east-1.amazonaws.com", false, true);
        updateRegion(region12, str45, "s3.amazonaws.com", false, true);
        updateRegion(region12, ServiceAbbreviations.SimpleDB, "sdb.amazonaws.com", false, true);
        updateRegion(region12, str12, "sns.us-east-1.amazonaws.com", false, true);
        updateRegion(region12, str10, "sqs.us-east-1.amazonaws.com", false, true);
        updateRegion(region12, ServiceAbbreviations.STS, str13, false, true);
        Region region13 = new Region("us-east-2", str46);
        ret3.add(region13);
        updateRegion(region13, str47, "autoscaling.us-east-2.amazonaws.com", false, true);
        updateRegion(region13, str22, "cognito-identity.us-east-2.amazonaws.com", false, true);
        updateRegion(region13, str37, "cognito-idp.us-east-2.amazonaws.com", false, true);
        updateRegion(region13, str33, "cognito-sync.us-east-2.amazonaws.com", false, true);
        updateRegion(region13, ServiceAbbreviations.Dynamodb, "dynamodb.us-east-2.amazonaws.com", false, true);
        updateRegion(region13, ServiceAbbreviations.EC2, "ec2.us-east-2.amazonaws.com", false, true);
        updateRegion(region13, str43, "elasticloadbalancing.us-east-2.amazonaws.com", false, true);
        updateRegion(region13, "firehose", "firehose.us-east-2.amazonaws.com", false, true);
        updateRegion(region13, str35, "iot.us-east-2.amazonaws.com", false, true);
        updateRegion(region13, str48, "kinesis.us-east-2.amazonaws.com", false, true);
        updateRegion(region13, str44, "kms.us-east-2.amazonaws.com", false, true);
        updateRegion(region13, str42, "lambda.us-east-2.amazonaws.com", false, true);
        String str49 = str38;
        updateRegion(region13, str49, "logs.us-east-2.amazonaws.com", false, true);
        updateRegion(region13, str29, "polly.us-east-2.amazonaws.com", false, true);
        String str50 = str29;
        String str51 = str45;
        updateRegion(region13, str51, "s3.us-east-2.amazonaws.com", false, true);
        updateRegion(region13, str12, "sns.us-east-2.amazonaws.com", false, true);
        updateRegion(region13, str10, "sqs.us-east-2.amazonaws.com", false, true);
        updateRegion(region13, ServiceAbbreviations.STS, str13, false, true);
        Region region14 = new Region("us-west-1", str46);
        ret3.add(region14);
        String str52 = str47;
        String str53 = str46;
        updateRegion(region14, str52, "autoscaling.us-west-1.amazonaws.com", false, true);
        updateRegion(region14, ServiceAbbreviations.Dynamodb, "dynamodb.us-west-1.amazonaws.com", false, true);
        updateRegion(region14, ServiceAbbreviations.EC2, "ec2.us-west-1.amazonaws.com", false, true);
        String str54 = ServiceAbbreviations.EC2;
        String str55 = str43;
        updateRegion(region14, str55, "elasticloadbalancing.us-west-1.amazonaws.com", false, true);
        updateRegion(region14, str48, "kinesis.us-west-1.amazonaws.com", false, true);
        updateRegion(region14, str44, "kms.us-west-1.amazonaws.com", false, true);
        updateRegion(region14, str42, "lambda.us-west-1.amazonaws.com", false, true);
        updateRegion(region14, str49, "logs.us-west-1.amazonaws.com", false, true);
        String str56 = str49;
        String str57 = str50;
        updateRegion(region14, str57, "polly.us-west-1.amazonaws.com", false, true);
        updateRegion(region14, str51, "s3.us-west-1.amazonaws.com", false, true);
        String str58 = str51;
        updateRegion(region14, ServiceAbbreviations.SimpleDB, "sdb.us-west-1.amazonaws.com", false, true);
        updateRegion(region14, str12, "sns.us-west-1.amazonaws.com", false, true);
        updateRegion(region14, str10, "sqs.us-west-1.amazonaws.com", false, true);
        updateRegion(region14, ServiceAbbreviations.STS, str13, false, true);
        Region region15 = new Region("us-west-2", str53);
        List<Region> ret4 = ret3;
        ret4.add(region15);
        updateRegion(region15, str52, "autoscaling.us-west-2.amazonaws.com", false, true);
        String str59 = str52;
        updateRegion(region15, str22, "cognito-identity.us-west-2.amazonaws.com", false, true);
        updateRegion(region15, str37, "cognito-idp.us-west-2.amazonaws.com", false, true);
        updateRegion(region15, str33, "cognito-sync.us-west-2.amazonaws.com", false, true);
        updateRegion(region15, str31, "data.iot.us-west-2.amazonaws.com", false, true);
        updateRegion(region15, ServiceAbbreviations.Dynamodb, "dynamodb.us-west-2.amazonaws.com", false, true);
        String str60 = str54;
        updateRegion(region15, str60, "ec2.us-west-2.amazonaws.com", false, true);
        updateRegion(region15, str55, "elasticloadbalancing.us-west-2.amazonaws.com", false, true);
        String str61 = str55;
        updateRegion(region15, "email", "email.us-west-2.amazonaws.com", false, true);
        updateRegion(region15, "firehose", "firehose.us-west-2.amazonaws.com", false, true);
        String str62 = str35;
        updateRegion(region15, str62, "iot.us-west-2.amazonaws.com", false, true);
        updateRegion(region15, str48, "kinesis.us-west-2.amazonaws.com", false, true);
        updateRegion(region15, str44, "kms.us-west-2.amazonaws.com", false, true);
        updateRegion(region15, str42, "lambda.us-west-2.amazonaws.com", false, true);
        String str63 = str44;
        String str64 = str56;
        updateRegion(region15, str64, "logs.us-west-2.amazonaws.com", false, true);
        updateRegion(region15, str57, "polly.us-west-2.amazonaws.com", false, true);
        String str65 = str57;
        updateRegion(region15, "rekognition", "rekognition.us-west-2.amazonaws.com", false, true);
        updateRegion(region15, str58, "s3.us-west-2.amazonaws.com", false, true);
        updateRegion(region15, ServiceAbbreviations.SimpleDB, "sdb.us-west-2.amazonaws.com", false, true);
        updateRegion(region15, str12, "sns.us-west-2.amazonaws.com", false, true);
        updateRegion(region15, str10, "sqs.us-west-2.amazonaws.com", false, true);
        updateRegion(region15, ServiceAbbreviations.STS, str13, false, true);
        Region region16 = new Region("cn-north-1", "amazonaws.com.cn");
        ret4.add(region16);
        String str66 = str59;
        updateRegion(region16, str66, "autoscaling.cn-north-1.amazonaws.com.cn", false, true);
        String str67 = str13;
        updateRegion(region16, str22, "cognito-identity.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region16, ServiceAbbreviations.Dynamodb, "dynamodb.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region16, str60, "ec2.cn-north-1.amazonaws.com.cn", false, true);
        String str68 = str61;
        updateRegion(region16, str68, "elasticloadbalancing.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region16, str62, "iot.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region16, str48, "kinesis.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region16, str42, "lambda.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region16, str64, "logs.cn-north-1.amazonaws.com.cn", false, true);
        String str69 = str62;
        String str70 = str58;
        updateRegion(region16, str70, "s3.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region16, str12, "sns.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region16, str10, "sqs.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region16, ServiceAbbreviations.STS, "sts.cn-north-1.amazonaws.com.cn", false, true);
        Region region17 = new Region("cn-northwest-1", "amazonaws.com.cn");
        ret4.add(region17);
        updateRegion(region17, str66, "autoscaling.cn-northwest-1.amazonaws.com.cn", false, true);
        updateRegion(region17, ServiceAbbreviations.Dynamodb, "dynamodb.cn-northwest-1.amazonaws.com.cn", false, true);
        updateRegion(region17, str60, "ec2.cn-northwest-1.amazonaws.com.cn", false, true);
        updateRegion(region17, str68, "elasticloadbalancing.cn-northwest-1.amazonaws.com.cn", false, true);
        updateRegion(region17, str48, "kinesis.cn-northwest-1.amazonaws.com.cn", false, true);
        updateRegion(region17, str64, "logs.cn-northwest-1.amazonaws.com.cn", false, true);
        updateRegion(region17, str70, "s3.cn-northwest-1.amazonaws.com.cn", false, true);
        updateRegion(region17, str12, "sns.cn-northwest-1.amazonaws.com.cn", false, true);
        updateRegion(region17, str10, "sqs.cn-northwest-1.amazonaws.com.cn", false, true);
        updateRegion(region17, ServiceAbbreviations.STS, "sts.amazonaws.com.cn", false, true);
        String str71 = str53;
        Region region18 = new Region("us-gov-west-1", str71);
        ret4.add(region18);
        List<Region> ret5 = ret4;
        updateRegion(region18, str66, "autoscaling.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region18, ServiceAbbreviations.Dynamodb, "dynamodb.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region18, str60, "ec2.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region18, str68, "elasticloadbalancing.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region18, str48, "kinesis.us-gov-west-1.amazonaws.com", false, true);
        String str72 = str48;
        String str73 = str63;
        updateRegion(region18, str73, "kms.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region18, str42, "lambda.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region18, str64, "logs.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region18, "rekognition", "rekognition.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region18, str70, "s3.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region18, str12, "sns.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region18, str10, "sqs.us-gov-west-1.amazonaws.com", false, true);
        String str74 = str67;
        updateRegion(region18, ServiceAbbreviations.STS, str74, false, true);
        Region region19 = new Region("eu-north-1", str71);
        ret5.add(region19);
        updateRegion(region19, str66, "autoscaling.eu-north-1.amazonaws.com", false, true);
        updateRegion(region19, ServiceAbbreviations.Dynamodb, "dynamodb.eu-north-1.amazonaws.com", false, true);
        updateRegion(region19, str60, "ec2.eu-north-1.amazonaws.com", false, true);
        updateRegion(region19, str68, "elasticloadbalancing.eu-north-1.amazonaws.com", false, true);
        String str75 = str68;
        updateRegion(region19, "firehose", "firehose.eu-north-1.amazonaws.com", false, true);
        updateRegion(region19, str69, "iot.eu-north-1.amazonaws.com", false, true);
        String str76 = str72;
        updateRegion(region19, str76, "kinesis.eu-north-1.amazonaws.com", false, true);
        updateRegion(region19, str73, "kms.eu-north-1.amazonaws.com", false, true);
        updateRegion(region19, str42, "lambda.eu-north-1.amazonaws.com", false, true);
        String str77 = str42;
        String str78 = str64;
        updateRegion(region19, str78, "logs.eu-north-1.amazonaws.com", false, true);
        updateRegion(region19, str70, "s3.eu-north-1.amazonaws.com", false, true);
        updateRegion(region19, str12, "sns.eu-north-1.amazonaws.com", false, true);
        updateRegion(region19, str10, "sqs.eu-north-1.amazonaws.com", false, true);
        updateRegion(region19, ServiceAbbreviations.STS, str74, false, true);
        Region region20 = new Region("ap-east-1", str71);
        ret5.add(region20);
        updateRegion(region20, str66, "autoscaling.ap-east-1.amazonaws.com", false, true);
        updateRegion(region20, ServiceAbbreviations.Dynamodb, "dynamodb.ap-east-1.amazonaws.com", false, true);
        updateRegion(region20, str60, "ec2.ap-east-1.amazonaws.com", false, true);
        String str79 = str60;
        updateRegion(region20, str75, "elasticloadbalancing.ap-east-1.amazonaws.com", false, true);
        updateRegion(region20, "firehose", "firehose.ap-east-1.amazonaws.com", false, true);
        updateRegion(region20, str76, "kinesis.ap-east-1.amazonaws.com", false, true);
        updateRegion(region20, str73, "kms.ap-east-1.amazonaws.com", false, true);
        String str80 = str77;
        updateRegion(region20, str80, "lambda.ap-east-1.amazonaws.com", false, true);
        updateRegion(region20, str78, "logs.ap-east-1.amazonaws.com", false, true);
        String str81 = str78;
        String str82 = str65;
        updateRegion(region20, str82, "polly.ap-east-1.amazonaws.com", false, true);
        updateRegion(region20, str70, "s3.ap-east-1.amazonaws.com", false, true);
        updateRegion(region20, str12, "sns.ap-east-1.amazonaws.com", false, true);
        updateRegion(region20, str10, "sqs.ap-east-1.amazonaws.com", false, true);
        updateRegion(region20, ServiceAbbreviations.STS, str74, false, true);
        Region region21 = new Region("me-south-1", str71);
        List<Region> ret6 = ret5;
        ret6.add(region21);
        updateRegion(region21, str66, "autoscaling.me-south-1.amazonaws.com", false, true);
        updateRegion(region21, str22, "cognito-identity.me-south-1.amazonaws.com", false, true);
        updateRegion(region21, str37, "cognito-idp.me-south-1.amazonaws.com", false, true);
        updateRegion(region21, str33, "cognito-sync.me-south-1.amazonaws.com", false, true);
        updateRegion(region21, str31, "data.iot.me-south-1.amazonaws.com", false, true);
        updateRegion(region21, ServiceAbbreviations.Dynamodb, "dynamodb.me-south-1.amazonaws.com", false, true);
        updateRegion(region21, str79, "ec2.me-south-1.amazonaws.com", false, true);
        updateRegion(region21, str75, "elasticloadbalancing.me-south-1.amazonaws.com", false, true);
        updateRegion(region21, "firehose", "firehose.me-south-1.amazonaws.com", false, true);
        updateRegion(region21, str69, "iot.me-south-1.amazonaws.com", false, true);
        updateRegion(region21, str76, "kinesis.me-south-1.amazonaws.com", false, true);
        updateRegion(region21, str73, "kms.me-south-1.amazonaws.com", false, true);
        updateRegion(region21, str80, "lambda.me-south-1.amazonaws.com", false, true);
        updateRegion(region21, str81, "logs.me-south-1.amazonaws.com", false, true);
        updateRegion(region21, str82, "polly.me-south-1.amazonaws.com", false, true);
        updateRegion(region21, str70, "s3.me-south-1.amazonaws.com", false, true);
        updateRegion(region21, ServiceAbbreviations.SimpleDB, "sdb.me-south-1.amazonaws.com", false, true);
        updateRegion(region21, str12, "sns.me-south-1.amazonaws.com", false, true);
        updateRegion(region21, str10, "sqs.me-south-1.amazonaws.com", false, true);
        updateRegion(region21, ServiceAbbreviations.STS, str74, false, true);
        return ret6;
    }

    private static void updateRegion(Region region, String service, String host, boolean http, boolean https) {
        Map<String, String> serviceEndpoints = region.getServiceEndpoints();
        Map<String, Boolean> httpSupport = region.getHttpSupport();
        Map<String, Boolean> httpsSupport = region.getHttpsSupport();
        serviceEndpoints.put(service, host);
        httpSupport.put(service, Boolean.valueOf(http));
        httpsSupport.put(service, Boolean.valueOf(https));
    }
}
