package com.leedarson.base.webservice.server;

import com.meituan.robust.ChangeQuickRedirect;
import com.yanzhenjie.andserver.framework.handler.b;
import com.yanzhenjie.andserver.framework.handler.f;
import com.yanzhenjie.andserver.framework.mapping.a;
import com.yanzhenjie.andserver.framework.mapping.c;
import java.util.LinkedHashMap;
import java.util.Map;
import org.glassfish.grizzly.http.server.Constants;

/* compiled from: PageControllerAdapter */
public final class i extends b {
    public static ChangeQuickRedirect changeQuickRedirect;
    private h h = new h();
    private Map<com.yanzhenjie.andserver.framework.mapping.b, f> i = new LinkedHashMap();

    public i() {
        com.yanzhenjie.andserver.framework.mapping.b mapping = new com.yanzhenjie.andserver.framework.mapping.b();
        com.yanzhenjie.andserver.framework.mapping.f path = new com.yanzhenjie.andserver.framework.mapping.f();
        path.a("/");
        mapping.h(path);
        c method = new c();
        method.a(Constants.GET);
        mapping.g(method);
        this.i.put(mapping, new l(this.h, mapping, new a(), (com.yanzhenjie.andserver.framework.cross.a) null));
        com.yanzhenjie.andserver.framework.mapping.b mapping2 = new com.yanzhenjie.andserver.framework.mapping.b();
        com.yanzhenjie.andserver.framework.mapping.f path2 = new com.yanzhenjie.andserver.framework.mapping.f();
        path2.a("/signin/");
        path2.a("/signin");
        mapping2.h(path2);
        c method2 = new c();
        method2.a(Constants.GET);
        mapping2.g(method2);
        this.i.put(mapping2, new s(this.h, mapping2, new a(), (com.yanzhenjie.andserver.framework.cross.a) null));
        com.yanzhenjie.andserver.framework.mapping.b mapping3 = new com.yanzhenjie.andserver.framework.mapping.b();
        com.yanzhenjie.andserver.framework.mapping.f path3 = new com.yanzhenjie.andserver.framework.mapping.f();
        path3.a("/location");
        path3.a("/location/");
        mapping3.h(path3);
        c method3 = new c();
        method3.a(Constants.GET);
        mapping3.g(method3);
        this.i.put(mapping3, new m(this.h, mapping3, new a(), (com.yanzhenjie.andserver.framework.cross.a) null));
        com.yanzhenjie.andserver.framework.mapping.b mapping4 = new com.yanzhenjie.andserver.framework.mapping.b();
        com.yanzhenjie.andserver.framework.mapping.f path4 = new com.yanzhenjie.andserver.framework.mapping.f();
        path4.a("/me");
        path4.a("/me/");
        mapping4.h(path4);
        c method4 = new c();
        method4.a(Constants.GET);
        mapping4.g(method4);
        this.i.put(mapping4, new o(this.h, mapping4, new a(), (com.yanzhenjie.andserver.framework.cross.a) null));
        com.yanzhenjie.andserver.framework.mapping.b mapping5 = new com.yanzhenjie.andserver.framework.mapping.b();
        com.yanzhenjie.andserver.framework.mapping.f path5 = new com.yanzhenjie.andserver.framework.mapping.f();
        path5.a("/Smart/");
        path5.a("/Smart");
        mapping5.h(path5);
        c method5 = new c();
        method5.a(Constants.GET);
        mapping5.g(method5);
        this.i.put(mapping5, new u(this.h, mapping5, new a(), (com.yanzhenjie.andserver.framework.cross.a) null));
        com.yanzhenjie.andserver.framework.mapping.b mapping6 = new com.yanzhenjie.andserver.framework.mapping.b();
        com.yanzhenjie.andserver.framework.mapping.f path6 = new com.yanzhenjie.andserver.framework.mapping.f();
        path6.a("/Scene/");
        path6.a("/Scene");
        mapping6.h(path6);
        c method6 = new c();
        method6.a(Constants.GET);
        mapping6.g(method6);
        this.i.put(mapping6, new q(this.h, mapping6, new a(), (com.yanzhenjie.andserver.framework.cross.a) null));
        com.yanzhenjie.andserver.framework.mapping.b mapping7 = new com.yanzhenjie.andserver.framework.mapping.b();
        com.yanzhenjie.andserver.framework.mapping.f path7 = new com.yanzhenjie.andserver.framework.mapping.f();
        path7.a("/Security");
        path7.a("/Security/");
        mapping7.h(path7);
        c method7 = new c();
        method7.a(Constants.GET);
        mapping7.g(method7);
        this.i.put(mapping7, new r(this.h, mapping7, new a(), (com.yanzhenjie.andserver.framework.cross.a) null));
        com.yanzhenjie.andserver.framework.mapping.b mapping8 = new com.yanzhenjie.andserver.framework.mapping.b();
        com.yanzhenjie.andserver.framework.mapping.f path8 = new com.yanzhenjie.andserver.framework.mapping.f();
        path8.a("/me/feedback/feedback/");
        path8.a("/me/feedback/feedback");
        mapping8.h(path8);
        c method8 = new c();
        method8.a(Constants.GET);
        mapping8.g(method8);
        this.i.put(mapping8, new j(this.h, mapping8, new a(), (com.yanzhenjie.andserver.framework.cross.a) null));
        com.yanzhenjie.andserver.framework.mapping.b mapping9 = new com.yanzhenjie.andserver.framework.mapping.b();
        com.yanzhenjie.andserver.framework.mapping.f path9 = new com.yanzhenjie.andserver.framework.mapping.f();
        path9.a("/Me");
        path9.a("/Me/");
        mapping9.h(path9);
        c method9 = new c();
        method9.a(Constants.GET);
        mapping9.g(method9);
        this.i.put(mapping9, new p(this.h, mapping9, new a(), (com.yanzhenjie.andserver.framework.cross.a) null));
        com.yanzhenjie.andserver.framework.mapping.b mapping10 = new com.yanzhenjie.andserver.framework.mapping.b();
        com.yanzhenjie.andserver.framework.mapping.f path10 = new com.yanzhenjie.andserver.framework.mapping.f();
        path10.a("/Account/SelectCountry/");
        path10.a("/Account/SelectCountry");
        mapping10.h(path10);
        c method10 = new c();
        method10.a(Constants.GET);
        mapping10.g(method10);
        this.i.put(mapping10, new n(this.h, mapping10, new a(), (com.yanzhenjie.andserver.framework.cross.a) null));
        com.yanzhenjie.andserver.framework.mapping.b mapping11 = new com.yanzhenjie.andserver.framework.mapping.b();
        com.yanzhenjie.andserver.framework.mapping.f path11 = new com.yanzhenjie.andserver.framework.mapping.f();
        path11.a("/Account/SignIn");
        path11.a("/Account/SignIn/");
        mapping11.h(path11);
        c method11 = new c();
        method11.a(Constants.GET);
        mapping11.g(method11);
        this.i.put(mapping11, new t(this.h, mapping11, new a(), (com.yanzhenjie.andserver.framework.cross.a) null));
        com.yanzhenjie.andserver.framework.mapping.b mapping12 = new com.yanzhenjie.andserver.framework.mapping.b();
        com.yanzhenjie.andserver.framework.mapping.f path12 = new com.yanzhenjie.andserver.framework.mapping.f();
        path12.a("/Me/Feedback");
        path12.a("/Me/Feedback/");
        mapping12.h(path12);
        c method12 = new c();
        method12.a(Constants.GET);
        mapping12.g(method12);
        this.i.put(mapping12, new k(this.h, mapping12, new a(), (com.yanzhenjie.andserver.framework.cross.a) null));
    }

    public Map<com.yanzhenjie.andserver.framework.mapping.b, f> g() {
        return this.i;
    }
}
