package org.spongycastle.asn1.misc;

import androidx.exifinterface.media.ExifInterface;
import org.spongycastle.asn1.ASN1ObjectIdentifier;

public interface MiscObjectIdentifiers {
    public static final ASN1ObjectIdentifier A;
    public static final ASN1ObjectIdentifier B;
    public static final ASN1ObjectIdentifier C;
    public static final ASN1ObjectIdentifier D;
    public static final ASN1ObjectIdentifier E;
    public static final ASN1ObjectIdentifier F;
    public static final ASN1ObjectIdentifier G;
    public static final ASN1ObjectIdentifier a;
    public static final ASN1ObjectIdentifier b;
    public static final ASN1ObjectIdentifier c;
    public static final ASN1ObjectIdentifier d;
    public static final ASN1ObjectIdentifier e;
    public static final ASN1ObjectIdentifier f;
    public static final ASN1ObjectIdentifier g;
    public static final ASN1ObjectIdentifier h;
    public static final ASN1ObjectIdentifier i;
    public static final ASN1ObjectIdentifier j;
    public static final ASN1ObjectIdentifier k;
    public static final ASN1ObjectIdentifier l;
    public static final ASN1ObjectIdentifier m;
    public static final ASN1ObjectIdentifier n;
    public static final ASN1ObjectIdentifier o;
    public static final ASN1ObjectIdentifier p;
    public static final ASN1ObjectIdentifier q;
    public static final ASN1ObjectIdentifier r;
    public static final ASN1ObjectIdentifier s;
    public static final ASN1ObjectIdentifier t;
    public static final ASN1ObjectIdentifier u;
    public static final ASN1ObjectIdentifier v = new ASN1ObjectIdentifier("1.3.6.1.4.1.188.7.1.1.2");
    public static final ASN1ObjectIdentifier w;
    public static final ASN1ObjectIdentifier x;
    public static final ASN1ObjectIdentifier y;
    public static final ASN1ObjectIdentifier z;

    static {
        ASN1ObjectIdentifier aSN1ObjectIdentifier = new ASN1ObjectIdentifier("2.16.840.1.113730.1");
        a = aSN1ObjectIdentifier;
        b = aSN1ObjectIdentifier.o("1");
        c = aSN1ObjectIdentifier.o(ExifInterface.GPS_MEASUREMENT_2D);
        d = aSN1ObjectIdentifier.o(ExifInterface.GPS_MEASUREMENT_3D);
        e = aSN1ObjectIdentifier.o("4");
        f = aSN1ObjectIdentifier.o("7");
        g = aSN1ObjectIdentifier.o("8");
        h = aSN1ObjectIdentifier.o("12");
        i = aSN1ObjectIdentifier.o("13");
        ASN1ObjectIdentifier aSN1ObjectIdentifier2 = new ASN1ObjectIdentifier("2.16.840.1.113733.1");
        j = aSN1ObjectIdentifier2;
        k = aSN1ObjectIdentifier2.o("6.3");
        l = aSN1ObjectIdentifier2.o("6.9");
        m = aSN1ObjectIdentifier2.o("6.11");
        n = aSN1ObjectIdentifier2.o("6.13");
        o = aSN1ObjectIdentifier2.o("6.15");
        p = aSN1ObjectIdentifier2.o("8.1");
        ASN1ObjectIdentifier aSN1ObjectIdentifier3 = new ASN1ObjectIdentifier("2.16.840.1.113719");
        q = aSN1ObjectIdentifier3;
        r = aSN1ObjectIdentifier3.o("1.9.4.1");
        ASN1ObjectIdentifier aSN1ObjectIdentifier4 = new ASN1ObjectIdentifier("1.2.840.113533.7");
        s = aSN1ObjectIdentifier4;
        t = aSN1ObjectIdentifier4.o("65.0");
        u = aSN1ObjectIdentifier4.o("66.10");
        ASN1ObjectIdentifier aSN1ObjectIdentifier5 = new ASN1ObjectIdentifier("1.3.6.1.4.1.3029");
        w = aSN1ObjectIdentifier5;
        ASN1ObjectIdentifier o2 = aSN1ObjectIdentifier5.o("1");
        x = o2;
        y = o2.o("1.1");
        z = o2.o("1.2");
        A = o2.o("1.3");
        B = o2.o("1.4");
        ASN1ObjectIdentifier aSN1ObjectIdentifier6 = new ASN1ObjectIdentifier("1.3.6.1.4.1.1722.12.2");
        C = aSN1ObjectIdentifier6;
        D = aSN1ObjectIdentifier6.o("1.5");
        E = aSN1ObjectIdentifier6.o("1.8");
        F = aSN1ObjectIdentifier6.o("1.12");
        G = aSN1ObjectIdentifier6.o("1.16");
    }
}
