package org.spongycastle.asn1.nist;

import androidx.exifinterface.media.ExifInterface;
import androidx.room.RoomMasterTable;
import com.sensorsdata.analytics.android.sdk.data.adapter.DbParams;
import org.spongycastle.asn1.ASN1ObjectIdentifier;

public interface NISTObjectIdentifiers {
    public static final ASN1ObjectIdentifier A;
    public static final ASN1ObjectIdentifier B;
    public static final ASN1ObjectIdentifier C;
    public static final ASN1ObjectIdentifier D;
    public static final ASN1ObjectIdentifier E;
    public static final ASN1ObjectIdentifier F;
    public static final ASN1ObjectIdentifier G;
    public static final ASN1ObjectIdentifier H;
    public static final ASN1ObjectIdentifier I;
    public static final ASN1ObjectIdentifier J;
    public static final ASN1ObjectIdentifier K;
    public static final ASN1ObjectIdentifier L;
    public static final ASN1ObjectIdentifier M;
    public static final ASN1ObjectIdentifier N;
    public static final ASN1ObjectIdentifier O;
    public static final ASN1ObjectIdentifier P;
    public static final ASN1ObjectIdentifier Q;
    public static final ASN1ObjectIdentifier R;
    public static final ASN1ObjectIdentifier S;
    public static final ASN1ObjectIdentifier T;
    public static final ASN1ObjectIdentifier U;
    public static final ASN1ObjectIdentifier V;
    public static final ASN1ObjectIdentifier W;
    public static final ASN1ObjectIdentifier X;
    public static final ASN1ObjectIdentifier Y;
    public static final ASN1ObjectIdentifier Z;
    public static final ASN1ObjectIdentifier a;
    public static final ASN1ObjectIdentifier a0;
    public static final ASN1ObjectIdentifier b;
    public static final ASN1ObjectIdentifier b0;
    public static final ASN1ObjectIdentifier c;
    public static final ASN1ObjectIdentifier c0;
    public static final ASN1ObjectIdentifier d;
    public static final ASN1ObjectIdentifier d0;
    public static final ASN1ObjectIdentifier e;
    public static final ASN1ObjectIdentifier e0;
    public static final ASN1ObjectIdentifier f;
    public static final ASN1ObjectIdentifier f0;
    public static final ASN1ObjectIdentifier g;
    public static final ASN1ObjectIdentifier g0;
    public static final ASN1ObjectIdentifier h;
    public static final ASN1ObjectIdentifier h0;
    public static final ASN1ObjectIdentifier i;
    public static final ASN1ObjectIdentifier i0;
    public static final ASN1ObjectIdentifier j;
    public static final ASN1ObjectIdentifier k;
    public static final ASN1ObjectIdentifier l;
    public static final ASN1ObjectIdentifier m;
    public static final ASN1ObjectIdentifier n;
    public static final ASN1ObjectIdentifier o;
    public static final ASN1ObjectIdentifier p;
    public static final ASN1ObjectIdentifier q;
    public static final ASN1ObjectIdentifier r;
    public static final ASN1ObjectIdentifier s;
    public static final ASN1ObjectIdentifier t;
    public static final ASN1ObjectIdentifier u;
    public static final ASN1ObjectIdentifier v;
    public static final ASN1ObjectIdentifier w;
    public static final ASN1ObjectIdentifier x;
    public static final ASN1ObjectIdentifier y;
    public static final ASN1ObjectIdentifier z;

    static {
        ASN1ObjectIdentifier aSN1ObjectIdentifier = new ASN1ObjectIdentifier("2.16.840.1.101.3.4");
        a = aSN1ObjectIdentifier;
        ASN1ObjectIdentifier o2 = aSN1ObjectIdentifier.o(ExifInterface.GPS_MEASUREMENT_2D);
        b = o2;
        c = o2.o("1");
        d = o2.o(ExifInterface.GPS_MEASUREMENT_2D);
        e = o2.o(ExifInterface.GPS_MEASUREMENT_3D);
        f = o2.o("4");
        g = o2.o("5");
        h = o2.o("6");
        i = o2.o("7");
        j = o2.o("8");
        k = o2.o(DbParams.GZIP_DATA_ENCRYPT);
        l = o2.o("10");
        m = o2.o("11");
        n = o2.o("12");
        o = o2.o("13");
        p = o2.o("14");
        q = o2.o("15");
        r = o2.o("16");
        ASN1ObjectIdentifier o3 = aSN1ObjectIdentifier.o("1");
        s = o3;
        t = o3.o("1");
        u = o3.o(ExifInterface.GPS_MEASUREMENT_2D);
        v = o3.o(ExifInterface.GPS_MEASUREMENT_3D);
        w = o3.o("4");
        x = o3.o("5");
        y = o3.o("6");
        z = o3.o("7");
        A = o3.o("8");
        B = o3.o("21");
        C = o3.o("22");
        D = o3.o("23");
        E = o3.o("24");
        F = o3.o("25");
        G = o3.o("26");
        H = o3.o("27");
        I = o3.o("28");
        J = o3.o("41");
        K = o3.o(RoomMasterTable.DEFAULT_ID);
        L = o3.o("43");
        M = o3.o("44");
        N = o3.o("45");
        O = o3.o("46");
        P = o3.o("47");
        Q = o3.o("48");
        ASN1ObjectIdentifier o4 = aSN1ObjectIdentifier.o(ExifInterface.GPS_MEASUREMENT_3D);
        R = o4;
        S = o4;
        T = o4.o("1");
        U = o4.o(ExifInterface.GPS_MEASUREMENT_2D);
        V = o4.o(ExifInterface.GPS_MEASUREMENT_3D);
        W = o4.o("4");
        X = o4.o("5");
        Y = o4.o("6");
        Z = o4.o("7");
        a0 = o4.o("8");
        b0 = o4.o(DbParams.GZIP_DATA_ENCRYPT);
        c0 = o4.o("10");
        d0 = o4.o("11");
        e0 = o4.o("12");
        f0 = o4.o("13");
        g0 = o4.o("14");
        h0 = o4.o("15");
        i0 = o4.o("16");
    }
}
